version: '3.3'
services:

  plex:
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=$DOCKER_PUID
      - PGID=$DOCKER_PGID
      - VERSION=latest
      - TZ=$SERVER_TIMEZONE
    volumes:
      - '$STORAGE_CONFIG_DIR/plex:/config'
      - '$STORAGE_MEDIA_DIR:/media'
    tmpfs: /transcode
    image: lscr.io/linuxserver/plex
