cameras:
  patio:
    width: 640
    height: 480
    record:
      enabled: true
      retain_days: 7
    snapshots:
      enabled: true
      bounding_box: true
      required_zones:
        - deck_stairs
        - back_door
      retain:
        default: 2
        objects:
          person: 14
    clips:
      enabled: true
      required_zones:
        - deck_stairs
        - back_door
      retain:
        default: 2
        objects:
          person: 14
    objects:
      track:
        - person
        - cat
        - dog
        - mouse
    zones:
      patio_couch:
        coordinates: 265,108,319,177,328,259,170,298,131,136
      deck_stairs:
        coordinates: 500,173,573,269,433,320,367,257,300,76,417,80
      back_door:
        coordinates: 179,422,67,99,0,111,0,256,85,480
    motion:
      mask:
        - 421,480,416,443,198,437,197,480
        - 0,267,0,480,80,480
        - 0,0,0,102,187,81,415,71,478,112,640,189,640,0
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@{FRIGATE_PATIO_IP}:554//h264Preview_01_main
          roles:
            - clips
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@{FRIGATE_PATIO_IP}:554//h264Preview_01_sub
          roles:
            - record
            - rtmp
            - detect
  garage:
    width: 640
    height: 480
    record:
      enabled: true
      retain_days: 7
    snapshots:
      enabled: true
      bounding_box: true
      required_zones:
        - garage_door
        - trash_cans
        - garage_entry
      retain:
        default: 2
        objects:
          person: 14
    clips:
      enabled: true
      required_zones:
        - garage_door
        - trash_cans
        - garage_entry
      retain:
        default: 2
        objects:
          person: 14
    objects:
      track:
        - person
        - dog
    zones:
      garage_door:
        coordinates: 81,0,0,0,0,480,87,480
      garage_entry:
        coordinates: 432,128,500,0,583,65,528,181
      trash_cans:
        coordinates: 340,0,300,113,451,139,492,49
    motion:
      mask:
        - 463,0,640,0,640,98
        - 67,120,300,113,416,480,74,480
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@{FRIGATE_GARAGE_IP}:554//h264Preview_01_main
          roles:
           - clips
        - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@{FRIGATE_GARAGE_IP}:554//h264Preview_01_sub
          roles:
           - detect
           - rtmp
           - record
  # doorbell:
  #   width: 640
  #   height: 480
  #   fps: 5
  #   snapshots:
  #     enabled: true
  #     bounding_box: true
  #     required_zones:
  #       - front_door
  #     retain:
  #       default: 2
  #       objects:
  #         person: 14
  #   clips:
  #     enabled: true
  #     required_zones:
  #       - front_door
  #     retain:
  #       default: 2
  #       objects:
  #         person: 14
  #   objects:
  #     track:
  #       - person
  #       - dog
  #   zones:
  #     front_door:
  #       - 0,0,0,1920,2560,1920,2560,0
  #   motion:
  #     mask:
  #       - 1695,1920,1695,1830,835,1830,835,1920
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@{FRIGATE_DOORBELL_IP}:554//h264Preview_01_main
  #         roles:
  #          - clips
  #          - record
  #       - path: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@{FRIGATE_DOORBELL_IP}:554//h264Preview_01_sub
  #         roles:
  #          - detect
  #          - rtmp

mqtt:
  host: homeassistant.flanneryonline.com
  topic_prefix: camera
  user: homeadmin
  password: '{FRIGATE_MQTT_PASSWORD}'

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu