cameras:
  patio:
    detect:
      width: 2304
      height: 1296
      fps: 2
    record:
      enabled: true
      retain_days: 1
      events:
        required_zones:
          - deck_stairs
          - back_door
        retain:
          default: 1
          objects:
            person: 7
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 1
        objects:
          person: 14
    objects:
      track:
        - person
        - cat
        - dog
        - mouse
    zones:
      back_door:
        coordinates: 603,1296,347,481,0,344,0,732,270,1296
      deck_stairs:
        coordinates: 1765,429,1832,669,1619,806,1315,679,1063,193,1538,190
      patio_couch:
        coordinates: 979,320,1107,408,1093,555,1163,665,977,729,658,736,518,582,536,365
    motion:
      mask:
        - 710,1280,1560,1280,1560,1210,710,1210
    ffmpeg:
      inputs:
        - path: rtmp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@{FRIGATE_PATIO_IP}/bcs/channel0_main.bcs?token=sdasdasd&channel=0&stream=0&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
          roles:
            - record
            - rtmp
            - detect
  garage:
    detect:
      width: 2304
      height: 1296
      fps: 2
    record:
      enabled: true
      retain_days: 1
      events:
        required_zones:
          - garage_door
          - trash_cans
          - garage_entry
        retain:
          default: 1
          objects:
            person: 7
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 1
        objects:
          person: 14
    objects:
      track:
        - person
        - dog
    zones:
      garage_door:
        coordinates: 357,0,0,0,0,1296,262,1296
      garage_entry:
        coordinates: 1552,455,1866,77,2080,161,1880,578
      trash_cans:
        coordinates: 1444,0,1214,251,1407,357,1693,344,1808,156
    motion:
      mask:
        - 710,1280,1560,1280,1560,1210,710,1210
    ffmpeg:
      inputs:
        - path: rtmp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@{FRIGATE_GARAGE_IP}/bcs/channel0_main.bcs?token=sdasdasd&channel=0&stream=0&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
          roles:
           - detect
           - rtmp
           - record
  doorbell:
    detect:
      width: 2304
      height: 1296
      fps: 2
    record:
      enabled: true
      retain_days: 1
      events:
        required_zones:
          - front_door
        retain:
          default: 1
          objects:
            person: 7
    snapshots:
      enabled: true
      bounding_box: true
      required_zones:
        - front_door
      retain:
        default: 1
        objects:
          person: 14
    objects:
      track:
        - person
        - dog
    zones:
      front_door:
        coordinates: 0,0,0,1296,2304,1296,2304,0
    motion:
      mask:
        - 710,1280,1560,1280,1560,1210,710,1210
    ffmpeg:
      inputs:
        - path: rtmp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@{FRIGATE_DOORBELL_IP}/bcs/channel0_main.bcs?token=sdasdasd&channel=0&stream=0&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
          roles:
           - record
           - detect
           - rtmp

ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero

mqtt:
  host: homeassistant.flanneryonline.com
  topic_prefix: camera
  user: homeadmin
  password: '{FRIGATE_MQTT_PASSWORD}'

detectors:
  coral:
    type: edgetpu
    device: usb