version: '3.3'
services:
    proxy:
        container_name: proxy
        image: traefik
        networks:
            - proxy
        ports:
            - 80:80
            - 443:443
        labels:
            - "proxy.enable=true"
            - "proxy.http.routers.proxy.rule=Host(`proxy.flanneryonline.com`)"
            - "proxy.http.routers.proxy.middlewares=https-redirect@file"
            - "proxy.http.routers.proxy-secure.rule=Host(`proxy.flanneryonline.com`)"
            - "proxy.http.routers.proxy-secure.tls=true"
            - "proxy.http.routers.proxy-secure.tls.certresolver=leresolver"
            - "proxy.http.routers.proxy-secure.service=api@internal"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - $SERVER_INSTALL/configs/proxy:/etc/traefik
            - $STORAGE_CONFIG_DIR/traefik/acme.json:/acme.json

networks:
    proxy:
        external: true