#!/usr/bin/env bash

set -o errexit
set -o nounset

function pkg_init {

local altroot=${1:-${ALTROOT:-${altroot:-}}}

#copied from man page
if \
    chroot "${altroot}" \
    TMPDIR=/dev/null \
    ASSUME_ALWAYS_YES=yes \
    PACKAGESITE=file:///nonexistent \
    pkg info -x 'pkg(-devel)?$' >/dev/null 2>&1
then
    env ASSUME_ALWAYS_YES=YES pkg bootstrap
fi

#make sure bootstrap worked
if \
    chroot "${altroot}" \
    TMPDIR=/dev/null \
    ASSUME_ALWAYS_YES=yes \
    PACKAGESITE=file:///nonexistent \
    pkg info -x 'pkg(-devel)?$' >/dev/null 2>&1
then
    echo "pkg init failed."
    return 1
fi

chroot "${altroot}" \
TMPDIR=/dev/null \
ASSUME_ALWAYS_YES=yes \
pkg update >/dev/null 2>&1

chroot "${altroot}" \
TMPDIR=/dev/null \
ASSUME_ALWAYS_YES=yes \
pkg upgrade >/dev/null 2>&1

echo "Installing portmaster."
chroot "${altroot}" make \
    -C /usr/ports/ports-mgmt/portmaster \
    -DBATCH install clean \
    >/dev/null 2>&1

return 0

}
