#!/usr/bin/env bash

set -o errexit
set -o nounset

function ssmtp_conf_init {

local altroot=${1:-${ALTROOT:-${altroot:-}}}

local password=""
while [[ -z "${password// }" ]]
do
    read -s -p "Enter ssmtp password: " password
    if [[ -z "${password// }" ]] 
    then 
        echo "    must not be blank! try again..."
    fi
done

mkdir -p "${altroot}/usr/local/etc/ssmtp"
echo "root=pat@flanneryonline.com" > "${altroot}/usr/local/etc/ssmtp/ssmtp.conf"
echo "mailhub=smtp.mail.wowway.com" >> "${altroot}/usr/local/etc/ssmtp/ssmtp.conf"
echo "rewriteDomain=flanneryonline.com" >> "${altroot}/usr/local/etc/ssmtp/ssmtp.conf"
echo "AuthUser=pflannery" >> "${altroot}/usr/local/etc/ssmtp/ssmtp.conf"
echo "AuthPass=${password}" >> "${altroot}/usr/local/etc/ssmtp/ssmtp.conf"

echo "root:pat@flanneryonline.com" > "${altroot}/usr/local/etc/ssmtp/revaliases"
echo "homeadmin:pat@flanneryonline.com" > "${altroot}/usr/local/etc/ssmtp/revaliases"

echo "    ssmtp.conf created"
return 0
}
