#!/usr/bin/env bash

set -o errexit
set -o nounset

function sysrc_init {

echo "Configuring host software."
#chroot "${altroot}" python3 -m ensurepip >/dev/null 2>&1
#chroot "${altroot}" pip3 install jedi >/dev/null 2>&1
sysrc -R "${altroot}" zfs_enable="YES" >/dev/null 2>&1
sysrc -R "${altroot}" defaultrouter="${gateway}" >/dev/null 2>&1
sysrc -R "${altroot}" sendmail_enable="NO" >/dev/null 2>&1
sysrc -R "${altroot}" sendmail_submit_enable="NO" >/dev/null 2>&1
sysrc -R "${altroot}" sendmail_outbound_enable="NO" >/dev/null 2>&1
sysrc -R "${altroot}" sendmail_msp_queue_enable="NO" >/dev/null 2>&1
sysrc -R "${altroot}" hostname="${fqdn}" >/dev/null 2>&1
sysrc -R "${altroot}" cloned_interfaces="lagg0" >/dev/null 2>&1
sysrc -R "${altroot}" jail_enable="YES" >/dev/null 2>&1
for net in $(ifconfig | grep -v LOOPBACK | grep flags | cut -d: -f1)
do
    sysrc -R "${altroot}" "ifconfig_${net}=\"up\"" >/dev/null 2>&1
    lag_string="${lag_string:-"laggproto lacp"} laggport ${net}"
done
sysrc -R "${altroot}" ifconfig_lagg0="inet ${host_ip} netmask ${subnet} ${lag_string}" >/dev/null 2>&1

return 0
}
