#!/usr/bin/env bash

set -o errexit
set -o nounset

function user_init {

local altroot=${1:-${ALTROOT:-${altroot:-}}}

echo "starting user_init at ${altroot}"

echo "    host user/group setup"
chroot "${altroot}" pw useradd -n "media" -u 1001 -s "/usr/sbin/nologin" -d "/nonexistent" -w no
chroot "${altroot}" pw useradd -n "homeadmin" -u 5000 -s "/usr/local/bin/zsh" -G "wheel, media" -w no
chroot "${altroot}" passwd "root"
chroot "${altroot}" passwd "homeadmin"

echo "    git clone dotfiles/server files"
chroot "${altroot}" cd /usr/home/homeadmin && git clone https://github.com/flanneryonline/dotfiles.git
chroot "${altroot}" cd /usr/home/homeadmin && git clone https://github.com/flanneryonline/server.git

echo "user_init complete"
return 0
}
