version: '3.3'
services:
    plex:
        container_name: plex
        ports:
            - '32400:32400/tcp'
            - '3005:3005/tcp'
            - '8324:8324/tcp'
            - '32469:32469/tcp'
            - '1900:1900/udp'
            - '32410:32410/udp'
            - '32412:32412/udp'
            - '32413:32413/udp'
            - '32414:32414/udp'
        environment:
            - PUID=$DOCKER_PUID
            - PGID=$DOCKER_PGID
            - VERSION=docker
            - TZ=$SERVER_TIMEZONE
        volumes:
            - '$STORAGE_CONFIG_DIR/plex:/config'
            - '$STORAGE_MEDIA_DIR:/media'
        image: ghcr.io/linuxserver/plex

    emby:
        container_name: emby
        ports:
            - '8096:8096'
        environment:
            - UID=$DOCKER_PUID
            - GID=$DOCKER_PGID
        volumes:
            - '$STORAGE_CONFIG_DIR/emby:/config'
            - '$STORAGE_MEDIA_DIR:/media'
        tmpfs: /transcode
        image: emby/embyserver


    nzbget:
        container_name: nzbget
        ports:
            - '6789:6789'
        healthcheck:
            test: curl --max-time 5 -Lsf http://127.0.0.1:6789 >/dev/null
            interval: 5s
            timeout: 5s
            start_period: 5s
        environment:
            - PUID=$DOCKER_PUID
            - PGID=$DOCKER_PGID
            - TZ=$SERVER_TIMEZONE
        volumes:
            - '$STORAGE_CONFIG_DIR/nzbget:/config'
            - '$STORAGE_DOWNLOAD_DIR:/downloads'
        image: ghcr.io/linuxserver/nzbget

    prowlarr:
        container_name: prowlarr
        ports:
            - '9696:9696'
        healthcheck:
            test: curl --max-time 5 -Lsf http://127.0.0.1:9696 >/dev/null
            interval: 5s
            timeout: 5s
            start_period: 5s
        environment:
            - PUID=$DOCKER_PUID
            - PGID=$DOCKER_PGID
            - TZ=$SERVER_TIMEZONE
        volumes:
            - '$STORAGE_CONFIG_DIR/prowlarr:/config'
        image: ghcr.io/linuxserver/prowlarr:develop

    radarr:
        container_name: radarr
        ports:
            - '7878:7878'
        healthcheck:
            test: curl --max-time 5 -Lsf http://127.0.0.1:7878 >/dev/null
            interval: 5s
            timeout: 5s
            start_period: 5s
        environment:
            - PUID=$DOCKER_PUID
            - PGID=$DOCKER_PGID
            - TZ=$SERVER_TIMEZONE
        volumes:
            - '$STORAGE_CONFIG_DIR/radarr:/config'
            - '$STORAGE_MEDIA_DIR/movies:/movies'
            - '$STORAGE_DOWNLOAD_DIR:/downloads'
        depends_on:
            - nzbget
            - prowlarr
            - plex
            - emby
        image: ghcr.io/linuxserver/radarr

    radarr4k:
        container_name: radarr4k
        ports:
            - '7888:7888'
        healthcheck:
            test: curl --max-time 5 -Lsf http://127.0.0.1:7888 >/dev/null
            interval: 5s
            timeout: 5s
            start_period: 5s
        environment:
            - PUID=$DOCKER_PUID
            - PGID=$DOCKER_PGID
            - TZ=$SERVER_TIMEZONE
        volumes:
            - '$STORAGE_CONFIG_DIR/radarr4k:/config'
            - '$STORAGE_MEDIA_DIR/movies:/movies'
            - '$STORAGE_DOWNLOAD_DIR:/downloads'
        depends_on:
            - nzbget
            - prowlarr
            - plex
            - emby
        image: ghcr.io/linuxserver/radarr

    sonarr:
        container_name: sonarr
        ports:
            - '8989:8989'
        healthcheck:
            test: curl --max-time 5 -Lsf http://127.0.0.1:8989 >/dev/null
            interval: 5s
            timeout: 5s
            start_period: 5s
        environment:
            - PUID=$DOCKER_PUID
            - PGID=$DOCKER_PGID
            - TZ=$SERVER_TIMEZONE
        volumes:
            - '$STORAGE_CONFIG_DIR/sonarr:/config'
            - '$STORAGE_MEDIA_DIR/shows:/shows'
            - '$STORAGE_DOWNLOAD_DIR:/downloads'
        depends_on:
            - nzbget
            - prowlarr
            - plex
            - emby
        image: ghcr.io/linuxserver/sonarr

    sonarr4k:
        container_name: sonarr4k
        ports:
            - '8988:8988'
        healthcheck:
            test: curl --max-time 5 -Lsf http://127.0.0.1:8988 >/dev/null
            interval: 5s
            timeout: 5s
            start_period: 5s
        environment:
            - PUID=$DOCKER_PUID
            - PGID=$DOCKER_PGID
            - TZ=$SERVER_TIMEZONE
        volumes:
            - '$STORAGE_CONFIG_DIR/sonarr4k:/config'
            - '$STORAGE_MEDIA_DIR/shows:/shows'
            - '$STORAGE_DOWNLOAD_DIR:/downloads'
        depends_on:
            - nzbget
            - prowlarr
            - plex
            - emby
        image: ghcr.io/linuxserver/sonarr

    lidarr:
        container_name: lidarr
        ports:
            - '8686:8686'
        healthcheck:
            test: curl --max-time 5 -Lsf http://127.0.0.1:8686 >/dev/null
            interval: 5s
            timeout: 5s
            start_period: 5s
        environment:
            - PUID=$DOCKER_PUID
            - PGID=$DOCKER_PGID
            - TZ=$SERVER_TIMEZONE
        volumes:
            - '$STORAGE_CONFIG_DIR/lidarr:/config'
            - '$STORAGE_MEDIA_DIR/audio/main:/music'
            - '$STORAGE_DOWNLOAD_DIR:/downloads'
        depends_on:
            - nzbget
            - prowlarr
            - plex
            - emby
        image: ghcr.io/linuxserver/lidarr