version: "3.8"
services:

  trigger:
    volumes:
      - /mnt/camera/@Snapshot:/aiinput
    environment:
      - TZ=$SERVER_TIMEZONE
    networks:
      - camera
    secrets:
      - triggers
      - settings
    image: danecreekphotography/node-deepstackai-trigger:latest
    restart: always
    depends_on:
      - deepstack-ai

  deepstack-ai:
    image: deepquestai/deepstack:latest
    restart: always
    networks:
      - camera
    volumes:
      - localstorage:/datastore
    environment:
      - VISION-DETECTION=True

  screenshots:
    image: nginx
    restart: always
    networks:
      - proxy
    # ports:
    #   - 5050:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.camera.loadbalancer.server.port=80"
      - "traefik.http.routers.camera.rule=Host(`camera.flanneryonline.com`)"
      - "traefik.http.routers.camera.middlewares=https-redirect@file"
      - "traefik.http.routers.camera.service=camera"
      - "traefik.http.routers.camera-secure.rule=Host(`camera.flanneryonline.com`)"
      - "traefik.http.routers.camera-secure.tls=true"
      - "traefik.http.routers.camera-secure.tls.certresolver=leresolver"
      - "traefik.http.routers.camera-secure.service=camera"
      - "traefik.docker.network=proxy"
    volumes:
      - /mnt/camera/@Snapshot/:/usr/share/nginx/html:ro

volumes:
  localstorage:

secrets:
  settings:
    file: $SERVER_INSTALL/configs/camera/settings.json
  triggers:
    file: $SERVER_INSTALL/configs/camera/triggers.json

networks:
    camera:
    proxy:
        external: true