version: "3.8"
services:

  trigger:
    volumes:
      - /mnt/camera/@Snapshot:/aiinput
    environment:
      - TZ=$SERVER_TIMEZONE
    ports:
      - 4242:4242
    secrets:
      - triggers
      - settings
    image: danecreekphotography/node-deepstackai-trigger:latest
    restart: always
    depends_on:
      - deepstack-ai

  deepstack-ai:
    image: deepquestai/deepstack:latest
    restart: always
    volumes:
      - localstorage:/datastore
    environment:
      - VISION-DETECTION=True

volumes:
  localstorage:

secrets:
  settings:
    file: $STORAGE_CONFIG_DIR/camera/settings.json
  triggers:
    file: $STORAGE_CONFIG_DIR/camera/triggers.json