#!/usr/bin/env bash

. /opt/server/environment
. /opt/server/include
version=1

check_version $version $0 && exit 0

[ -f /etc/apt/sources.list ] && rm /etc/apt/sources.list
touch /etc/apt/sources.list
[ ! -d /etc/apt/sources.list.d ] && mkdir -p /etc/apt/sources.list.d
[ $(ls -A /etc/apt/sources.list.d) ] && rm /etc/apt/sources.list.d/*

echo "deb [arch=amd64] $SERVER_DIST_URL $SERVER_DIST_RELEASE main universe" \
    >  /etc/apt/sources.list.d/$SERVER_DIST.$SERVER_DIST_RELEASE.list

echo "deb [arch=amd64] $SERVER_DIST_URL $SERVER_DIST_RELEASE-updates main universe" \
    >  /etc/apt/sources.list.d/$SERVER_DIST.$SERVER_DIST_RELEASE.updates.list

echo "deb [arch=amd64] $SERVER_DIST_URL $SERVER_DIST_RELEASE-security main universe" \
    >  /etc/apt/sources.list.d/$SERVER_DIST.$SERVER_DIST_RELEASE.security.list

set_version $version $0
exit 0
