#!/usr/bin/env bash

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=1

echo "Starting ${0##*/} patch on pid $$."
check_pid ${0##*/} $$ && exit 0
check_version $version ${0##*/} && exit 0

patch_requires "locale" 1
errorcheck && exit 1

[ -f /etc/apt/sources.list ] && rm /etc/apt/sources.list
touch /etc/apt/sources.list
[ ! -d /etc/apt/sources.list.d ] && mkdir -p /etc/apt/sources.list.d
[ "$(ls -A /etc/apt/sources.list.d)" ] && rm /etc/apt/sources.list.d/*

echo "deb [arch=amd64] $SERVER_DIST_URL $SERVER_DIST_RELEASE main universe" \
    >  /etc/apt/sources.list.d/$SERVER_DIST.$SERVER_DIST_RELEASE.list

echo "deb [arch=amd64] $SERVER_DIST_URL $SERVER_DIST_RELEASE-updates main universe" \
    >  /etc/apt/sources.list.d/$SERVER_DIST.$SERVER_DIST_RELEASE.updates.list

echo "deb [arch=amd64] $SERVER_DIST_URL $SERVER_DIST_RELEASE-security main universe" \
    >  /etc/apt/sources.list.d/$SERVER_DIST.$SERVER_DIST_RELEASE.security.list

apt-get update -qq
errorcheck && exit 1

set_version $version ${0##*/}
echo "Completed ${0##*/} patch on pid $$."
exit 0
