#!/usr/bin/env bash

set -e

export DEBIAN_FRONTEND=noninteractive
SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=1

check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

patch_requires "apt" 0
errorcheck && exit 1

echo "installing required packages"

apt-get install -qq --no-install-recommends \
    postfix \
    nfs-common \
    apt-transport-https \
    gnupg \
    grub-efi-amd64 \
    figlet \
    smartmontools \
    bash-completion \
    curl \
    git \
    gdisk \
    ntpdate \
    openssh-server
errorcheck && echoerr "error installing packages" && exit 1

set_version $version ${0##*/}
exit 0
