#!/usr/bin/env bash

set -e

export DEBIAN_FRONTEND=noninteractive
SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=2

check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

patch_requires "apt_install" 1
patch_requires "backup" 1
patch_requires "media_storage" 1

echo "getting system settings"

backup_enabled=$(get_server_setting "backup-enabled")
backup_enabled=${backup_enabled:-0}

echo "  backup_enabled=$backup_enabled"

if [ $backup_enabled -eq 1 ]
then
    for backup in configs movies shows unsorted shares
    do
        echo "removing old backup service for $backup"

        systemctl disable backup-$backup.service

        systemctl disable backup-$backup.timer
    done

    systemctl enable /opt/server/systemd/backup/media-backup.service
    systemctl enable /opt/server/systemd/backup/media-backup.timer

fi

set_version $version ${0##*/}
exit 0
