#!/usr/bin/env bash

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=1

echo "Starting ${0##*/} patch on pid $$."
check_pid ${0##*/} $$ && exit 0
check_version $version ${0##*/} && exit 0

patch_requires "backup" 1
errorcheck && exit 1

sync_enabled=$(get_server_setting "backup-sync-enabled")
sync_enabled=${sync_enabled:-0}
backup_enabled=$(get_server_setting "backup-enabled")
backup_enabled=${backup_enabled:-0}

if [ $backup_sync_enabled -eq 1 ] && [ $backup_enabled -eq 1 ]
then
    rsync -aqHXAp $BACKUP_MOUNT_LOCATION/media/movies/* "$STORAGE_MEDIA_DIR/movies/"
    errorcheck && echoerr "error while copying movies." && return 1
fi

set_version $version ${0##*/}
echo "Completed ${0##*/} patch on pid $$."
exit 0
