#!/usr/bin/env bash

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=1

check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

patch_requires "backup" 1
errorcheck && exit 1

sync_enabled=$(get_server_setting "backup-sync-enabled")
sync_enabled=${sync_enabled:-0}
backup_enabled=$(get_server_setting "backup-enabled")
backup_enabled=${backup_enabled:-0}

if [ $backup_sync_enabled -eq 1 ] && [ $backup_enabled -eq 1 ]
then
    rsync -aqHXAp $BACKUP_MOUNT_LOCATION/files/* "$STORAGE_SHARE_DIR/"
    errorcheck && echoerr "error while copying shares." && return 1
fi

set_version $version ${0##*/}
exit 0
