#!/usr/bin/env bash

set -e

export DEBIAN_FRONTEND=noninteractive
SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=0

check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

patch_requires "backup" 1
errorcheck && exit 1
patch_requires "media_storage" 1
errorcheck && exit 1

echo "getting system settings"

sync_enabled=$(get_server_setting "backup-sync-enabled")
sync_enabled=${sync_enabled:-0}
backup_enabled=$(get_server_setting "backup-enabled")
backup_enabled=${backup_enabled:-0}

echo "  sync_enabled=$sync_enabled"
echo "  backup_enabled=$backup_enabled"

if [ "$sync_enabled" -eq 1 ] && [ "$backup_enabled" -eq 1 ]
then
    echo "syncing movie data"
    rsync -aqHXAp $BACKUP_MOUNT_LOCATION/media/movies/* "$STORAGE_MEDIA_DIR/movies/"
    errorcheck && echoerr "error while copying movies." && return 1
fi

set_version $version ${0##*/}
exit 0
