#!/usr/bin/env bash

set -e

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=1

check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

patch_requires "apt_install" 1
errorcheck && exit 1
patch_requires "storage" 1
errorcheck && exit 1

echo "getting system settings"

link_backup=$(get_server_setting "link-backup")
link_backup=${link_backup:-0}
backup_enabled=$(get_server_setting "backup-enabled")
backup_enabled=${backup_enabled:-0}

echo "  link_backup=$link_backup"
echo "  backup_enabled=$backup_enabled"

if [ $backup_enabled -eq 1 ]
then
    echo "creating fstab entry for backup"
    echo "$BACKUP_ADDRESS:/$BACKUP_FOLDER $BACKUP_MOUNT_LOCATION nfs defaults,x-systemd.requires=nfs-client.target 0 0" >> "/etc/fstab"
fi

if [ $link_backup -eq 1 ]
then
    echo "creating backup links"
    ln -s $BACKUP_MOUNT_LOCATION/media $STORAGE_MEDIA_DIR
    ln -s $BACKUP_MOUNT_LOCATION/downloads $STORAGE_DOWNLOAD_DIR
    ln -s $BACKUP_MOUNT_LOCATION/configs $STORAGE_CONFIG_DIR
    ln -s $BACKUP_MOUNT_LOCATION/files $STORAGE_SHARE_DIR
fi

for backup in configs movies shows unsorted shares
do
    echo "creating backup service is systemd for $backup"

    [ ! -e /etc/systemd/system/backup-$backup.service ] && \
        ln -s /opt/server/systemd/backup/backup-$backup.service /etc/systemd/system/backup-$backup.service
    [ ! -h /etc/systemd/system/backup-$backup.service ] && \
        rm -r /etc/systemd/system/backup-$backup.service && \
        ln -s /opt/server/systemd/backup/backup-$backup.service /etc/systemd/system/backup-$backup.service

    [ ! -e /etc/systemd/system/backup-$backup.timer ] && \
        ln -s /opt/server/systemd/backup/backup-$backup.timer /etc/systemd/system/backup-$backup.timer
    [ ! -h /etc/systemd/system/backup-$backup.timer ] && \
        rm -r /etc/systemd/system/backup-$backup.timer && \
        ln -s /opt/server/systemd/backup/backup-$backup.timer /etc/systemd/system/backup-$backup.timer

    ! ischroot && systemctl daemon-reload

    if [ $SERVER_SERVICES_ENABLED -eq 1 ] && ! systemctl is-enabled backup-$backup.timer
    then
        echo "enabling $backup backup service"
        systemctl enabled backup-$backup.timer
    fi

    if [ $SERVER_SERVICES_ENABLED -eq 0 ] && systemctl is-enabled backup-$backup.timer
    then
        echo "disabling $backup backup service"
        systemctl disable backup-$backup.timer
    fi
done

set_version $version ${0##*/}
exit 0
