#!/usr/bin/env bash

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=1

echo "Starting ${0##*/} patch on pid $$."
check_pid ${0##*/} $$ && exit 0
check_version $version ${0##*/} && exit 0

patch_requires "apt" 1
errorcheck && exit 1
patch_requires "storage" 1
errorcheck && exit 1

apt-get install -qq --no-install-recommends nfs-common
errorcheck && echoerr "error installing nfs-common" && exit 1

link_backup=$(get_server_setting "link-backup")
link_backup=${link_backup:-0}
backup_enabled=$(get_server_setting "backup-enabled")
backup_enabled=${backup_enabled:-0}
services_enabled=$(get_server_setting "services-enabled")
services_enabled=${services_enabled:-0}

[ $backup_enabled -eq 1 ] && \
    echo "$BACKUP_ADDRESS:/$BACKUP_FOLDER $BACKUP_MOUNT_LOCATION nfs defaults,x-systemd.requires=nfs-client.target 0 0" >> "/etc/fstab"

if [ $link_backup -eq 1 ]
then
    ln -s $BACKUP_MOUNT_LOCATION/media $STORAGE_MEDIA_DIR
    ln -s $BACKUP_MOUNT_LOCATION/downloads $STORAGE_DOWNLOAD_DIR
    ln -s $BACKUP_MOUNT_LOCATION/configs $STORAGE_CONFIG_DIR
    ln -s $BACKUP_MOUNT_LOCATION/files $STORAGE_SHARE_DIR
fi

for backup in configs movies shows unsorted shares
do
    [ ! -e /etc/systemd/system/backup-$backup.service ] && \
        ln -s /opt/server/systemd/backup/backup-$backup.service /etc/systemd/system/backup-$backup.service
    [ ! -h /etc/systemd/system/backup-$backup.service ] && \
        rm -r /etc/systemd/system/backup-$backup.service && \
        ln -s /opt/server/systemd/backup/backup-$backup.service /etc/systemd/system/backup-$backup.service

    [ ! -e /etc/systemd/system/backup-$backup.timer ] && \
        ln -s /opt/server/systemd/backup/backup-$backup.timer /etc/systemd/system/backup-$backup.timer
    [ ! -h /etc/systemd/system/backup-$backup.timer ] && \
        rm -r /etc/systemd/system/backup-$backup.timer && \
        ln -s /opt/server/systemd/backup/backup-$backup.timer /etc/systemd/system/backup-$backup.timer

    systemctl daemon-reload

    [ $services_enabled -eq 1 ] && ! systemctl is-enabled backup-$backup.timer && systemctl enabled backup-$backup.timer
    [ $services_enabled -eq 0 ] && systemctl is-enabled backup-$backup.timer && systemctl disable backup-$backup.timer
done

set_version $version ${0##*/}
echo "Completed ${0##*/} patch on pid $$."
exit 0
