#!/usr/bin/env bash

. ${SERVER_INSTALL:-/opt}/server/include

#version is pulled from docker-compose

echo "Starting ${0##*/} patch on pid $$."
check_pid ${0##*/} $$ && exit 0

patch_requires "server" 1
errorcheck && exit 1

version=$(curl -ILsS -w "%{url_effective}" "https://github.com/docker/compose/releases/latest" -o /dev/null)
version=${version##*/}

check_version $version ${0##*/} && exit 0

patch_requires "docker" 1
errorcheck && exit 1
patch_requires "server" 1
errorcheck && exit 1

[ -f "/usr/bin/docker-compose" ] && rm "/usr/bin/docker-compose"
curl -fsSL "https://github.com/docker/compose/releases/download/$version/docker-compose-Linux-x86_64" \
    -o "/usr/bin/docker-compose"
errorcheck && echoerr "error downloading docker compose" && exit 1
chmod +x "/usr/bin/docker-compose"

if [ ! -f "/etc/bash_completion.d/docker-compose" ]
then
    [ ! -d "/etc/bash_completion.d" ] && mkdir -p "/etc/bash_completion.d"
    curl -fsSL "https://raw.githubusercontent.com/docker/compose/master/contrib/completion/bash/docker-compose" \
        -o "/etc/bash_completion.d/docker-compose"
    errorcheck && echoerr "error downloading docker compose bash completion" && exit 1
fi

set_version $version ${0##*/}
echo "Completed ${0##*/} patch on pid $$."
exit 0
