#!/usr/bin/env bash

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=1

echo "Starting ${0##*/} patch on pid $$."
check_pid ${0##*/} $$ && exit 0
check_version $version ${0##*/} && exit 0

patch_requires "apt" 1
errorcheck && exit 1

apt-get install -qq --no-install-recommends postfix
errorcheck && echoerr "error installing postfix" && exit 1

#setup email notification

set_version $version ${0##*/}
echo "Completed ${0##*/} patch on pid $$."
exit 0
