#!/usr/bin/env bash

set -e

export DEBIAN_FRONTEND=noninteractive
SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=0

check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

echo "running locale-gen"
locale-gen --purge en_US.UTF-8
errorcheck && echoerr "Error during locale-gen." && exit 1
echo "running update-locale"
update-locale LANG=en_US.UTF-8
errorcheck && echoerr "Error during update-locale." && exit 1

set_version $version ${0##*/}
exit 0
