#!/usr/bin/env bash

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=1

check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

locale-gen --purge en_US.UTF-8
errorcheck && echoerr "Error during locale-gen." && exit 1
update-locale LANG=en_US.UTF-8
errorcheck && echoerr "Error during update-locale." && exit 1

set_version $version ${0##*/}
exit 0
