#!/usr/bin/env bash

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=1

echo "Starting ${0##*/} patch on pid $$."
check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

locale-gen --purge en_US.UTF-8
errorcheck && echoerr "Error during locale-gen."  && exit 1
dpkg-reconfigure --frontend noninteractive locales
errorcheck && echoerr "Error during dpkg-reconfigure locales."  && exit 1
update-locale LANG=en_US.UTF-8
errorcheck && echoerr "Error during update-locale."  && exit 1

set_version $version ${0##*/}
echo "Completed ${0##*/} patch on pid $$."
exit 0
