#!/usr/bin/env bash

set -e

export DEBIAN_FRONTEND=noninteractive
SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=1

check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

patch_requires "media_storage" 1
patch_requires "docker" 1

systemctl enable /opt/server/systemd/docker/docker-create.service
systemctl start docker-create.service

for service in pia plex tautulli ombi deluge nzbget jackett hydra radarr sonarr
do
    systemctl enable /opt/server/systemd/docker/containers/$service.service
    systemctl start $service.service
done

set_version $version ${0##*/}
exit 0
