#!/usr/bin/env bash

set -e

export DEBIAN_FRONTEND=noninteractive
SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=1

check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

patch_requires "media_storage" 1
errorcheck && exit 1
patch_requires "docker_compose" 1
errorcheck && exit 1
patch_requires "backup_sync_configs" 1
errorcheck && exit 1
patch_requires "backup_sync_data" 1
errorcheck && exit 1
patch_requires "backup_sync_shows" 1
errorcheck && exit 1
patch_requires "backup_sync_movies" 1
errorcheck && exit 1
patch_requires "backup_sync_unsorted" 1
errorcheck && exit 1
patch_requires "docker" 1
errorcheck && exit 1
patch_requires "docker_compose" 1
errorcheck && exit 1

[ ! -d /etc/docker/compose ] && mkdir -p /etc/docker/compose
[ ! -e /etc/docker/compose/media-services ] && \
    ln -s /opt/server/docker-compose/media-services /etc/docker/compose/media-services
[ ! -h /etc/docker/compose/media-services ] && \
    rm -r /etc/docker/compose/media-services && \
    ln -s /opt/server/docker-compose/media-services /etc/docker/compose/media-services

[ ! -e /etc/systemd/system/media-services.service ] && \
    ln -s /opt/server/systemd/docker/media-services.service /etc/systemd/system/media-services.service
[ ! -h /etc/systemd/system/media-services.service ] && \
    rm -r /etc/systemd/system/media-services.service && \
    ln -s /opt/server/systemd/docker/media-services.service /etc/systemd/system/media-services.service

! ischroot && systemctl daemon-reload

if ! systemctl is-enabled media-services.service
then
    echo "enabling media-services.service"
    systemctl enable media-services.service
    ! ischroot && systemctl start media-services.service
fi

set_version $version ${0##*/}
exit 0
