#!/usr/bin/env bash

set -e

export DEBIAN_FRONTEND=noninteractive
SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=4

check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

patch_requires "apt_install" 2

echo "removing system motd files"
rm /etc/update-motd.d/*

echo "linking files to system motd directory"
[ ! -e /etc/update-motd.d/00-header ] && \
    ln -s /opt/server/motd/00-header /etc/update-motd.d/00-header
[ ! -h /etc/update-motd.d/00-header ] && \
    rm -r /etc/update-motd.d/00-header && \
    ln -s /opt/server/motd/00-header /etc/update-motd.d/00-header

[ ! -e /etc/update-motd.d/10-info ] && \
    ln -s /opt/server/motd/10-info /etc/update-motd.d/10-info
[ ! -h /etc/update-motd.d/10-info ] && \
    rm -r /etc/update-motd.d/10-info && \
    ln -s /opt/server/motd/10-info /etc/update-motd.d/10-info

[ ! -e /etc/update-motd.d/20-services ] && \
    ln -s /opt/server/motd/20-services /etc/update-motd.d/20-services
[ ! -h /etc/update-motd.d/20-services ] && \
    rm -r /etc/update-motd.d/20-services && \
    ln -s /opt/server/motd/20-services /etc/update-motd.d/20-services

[ ! -e /etc/update-motd.d/30-storage ] && \
    ln -s /opt/server/motd/30-storage /etc/update-motd.d/30-storage
[ ! -h /etc/update-motd.d/30-storage ] && \
    rm -r /etc/update-motd.d/30-storage && \
    ln -s /opt/server/motd/30-storage /etc/update-motd.d/30-storage

#echo "\"Samsung SSD 840 EVO 120G B\"                            190  C  \"Samsung SSD 840 EVO 120GB\"" >> /etc/hddtemp.db

systemctl disable motd-news.service
systemctl disable motd-news.timer
systemctl enable /opt/server/systemd/system/server-motd-update.timer
systemctl enable /opt/server/systemd/system/server-motd-update.service


set_version $version ${0##*/}
exit 0
