#!/usr/bin/env bash

. /opt/server/environment
. /opt/server/include

version=1

echo "Starting $0 patch on pid $$."
check_pid $0 $$ && exit 0
check_version $version $0 && exit 0

patch_requires "apt" 1
errorcheck && exit 1

apt-get install -qq --no-install-recommends figlet
errorcheck && echoerr "error installing figlet" && exit 1
apt-get install -qq --no-install-recommends smartmontools
errorcheck && echoerr "error installing smartmontools" && exit 1

chmod +x /opt/server/motd/*

rm /etc/update-motd.d/*

[ ! -e /etc/update-motd.d/00-header ] && \
    ln -s /opt/server/motd/00-header /etc/update-motd.d/00-header
[ ! -h /etc/update-motd.d/00-header ] && \
    rm -r /etc/update-motd.d/00-header && \
    ln -s /opt/server/motd/00-header /etc/update-motd.d/00-header

[ ! -e /etc/update-motd.d/10-info ] && \
    ln -s /opt/server/motd/10-info /etc/update-motd.d/10-info
[ ! -h /etc/update-motd.d/10-info ] && \
    rm -r /etc/update-motd.d/10-info && \
    ln -s /opt/server/motd/10-info /etc/update-motd.d/10-info

[ ! -e /etc/update-motd.d/20-services ] && \
    ln -s /opt/server/motd/20-services /etc/update-motd.d/20-services
[ ! -h /etc/update-motd.d/20-services ] && \
    rm -r /etc/update-motd.d/20-services && \
    ln -s /opt/server/motd/20-services /etc/update-motd.d/20-services

[ ! -e /etc/update-motd.d/30-zfs ] && \
    ln -s /opt/server/motd/30-zfs /etc/update-motd.d/30-zfs
[ ! -h /etc/update-motd.d/30-zfs ] && \
    rm -r /etc/update-motd.d/30-zfs && \
    ln -s /opt/server/motd/30-zfs /etc/update-motd.d/30-zfs

set_version $version $0
echo "Completed $0 patch on pid $$."
exit 0
