#!/usr/bin/env bash

. /opt/server/environment
. /opt/server/include

version=1

echo "Starting ${0##*/} patch on pid $$."
check_pid ${0##*/} $$ && exit 0
check_version $version ${0##*/} && exit 0

patch_requires "apt" 1
errorcheck && exit 1

apt-get install -qq --no-install-recommends bash-completion curl git
errorcheck && echoerr "error installing bash-completion, curl, git" && exit 1

[ ! -e /etc/systemd/system/server-update.service ] && \
    ln -s /opt/server/systemd/system/server-update.service /etc/systemd/system/server-update.service
[ ! -h /etc/systemd/system/server-update.service ] && \
    rm -r /etc/systemd/system/server-update.service && \
    ln -s /opt/server/systemd/system/server-update.service /etc/systemd/system/server-update.service

[ ! -e /etc/systemd/system/server-update.timer ] && \
    ln -s /opt/server/systemd/system/server-update.timer /etc/systemd/system/server-update.timer
[ ! -h /etc/systemd/system/server-update.timer ] && \
    rm -r /etc/systemd/system/server-update.timer && \
    ln -s /opt/server/systemd/system/server-update.timer /etc/systemd/system/server-update.timer

systemctl daemon-reload

[ $SERVER_SERVICES_ENABLED -eq 1 ] && ! systemctl is-enabled server-update.timer && systemctl enabled server-update.timer
[ $SERVER_SERVICES_ENABLED -eq 0 ] && systemctl is-enabled server-update.timer && systemctl disable server-update.timer

set_version $version ${0##*/}
echo "Completed ${0##*/} patch on pid $$."
exit 0
