#!/usr/bin/env bash

. /opt/server/environment
. /opt/server/include
version=1

check_version $version $0 && exit 0

[ ! -e /etc/systemd/system/server-update.service ] && \
    ln -s /opt/server/systemd/system/server-update.service /etc/systemd/system/server-update.service
[ ! -h /etc/systemd/system/server-update.service ] && \
    rm -r /etc/systemd/system/server-update.service && \
    ln -s /opt/server/systemd/system/server-update.service /etc/systemd/system/server-update.service

[ ! -e /etc/systemd/system/server-update.timer ] && \
    ln -s /opt/server/systemd/system/server-update.timer /etc/systemd/system/server-update.timer
[ ! -h /etc/systemd/system/server-update.timer ] && \
    rm -r /etc/systemd/system/server-update.timer && \
    ln -s /opt/server/systemd/system/server-update.timer /etc/systemd/system/server-update.timer

set_version $version $0
exit 0
