#!/usr/bin/env bash

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=1

check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

patch_requires "apt_install" 1
errorcheck && exit 1

echo "setting up update service in systemd"

[ ! -e /etc/systemd/system/server-update.service ] && \
    ln -s /opt/server/systemd/system/server-update.service /etc/systemd/system/server-update.service
[ ! -h /etc/systemd/system/server-update.service ] && \
    rm -r /etc/systemd/system/server-update.service && \
    ln -s /opt/server/systemd/system/server-update.service /etc/systemd/system/server-update.service

[ ! -e /etc/systemd/system/server-update.timer ] && \
    ln -s /opt/server/systemd/system/server-update.timer /etc/systemd/system/server-update.timer
[ ! -h /etc/systemd/system/server-update.timer ] && \
    rm -r /etc/systemd/system/server-update.timer && \
    ln -s /opt/server/systemd/system/server-update.timer /etc/systemd/system/server-update.timer

! ischroot && systemctl daemon-reload

if [ $SERVER_SERVICES_ENABLED -eq 1 ] && ! systemctl is-enabled server-update.timer
then
    echo "enabling server update service"
    systemctl enabled server-update.timer
fi

if [ $SERVER_SERVICES_ENABLED -eq 0 ] && systemctl is-enabled server-update.timer
then
    echo "disabling server update service"
    systemctl disable server-update.timer
fi

set_version $version ${0##*/}
exit 0
