#!/usr/bin/env bash

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=1

check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

patch_requires "apt" 1
errorcheck && exit 1

apt-get install -qq --no-install-recommends openssh-server
errorcheck && echoerr "error installing openssh-server" && exit 1

#setup ssh

set_version $version ${0##*/}
exit 0
