#!/usr/bin/env bash

set -e

export DEBIAN_FRONTEND=noninteractive
SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=2

check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

patch_requires "apt_install" 1

echo "getting system settings"

slow_storage_enabled=$(get_server_setting "slow-storage-enabled")
slow_storage_enabled=${slow_storage_enabled:-0}
slow_disks=$(get_server_setting "slow-disks")
slow_disks=${slow_disks:-}

echo "  slow_storage_enabled=$slow_storage_enabled"
echo "  slow_disks=$slow_disks"

if ! zpool status $SLOW_STORAGE_POOL >/dev/null 2>&1 && \
    [ $slow_storage_enabled -eq 1 ] && \
    [ ! -z "$slow_disks" ]
then
    echo "creating slow storage pool"
    slow_disk_list=
    for slow_disk in $slow_disks; do
        echo "clearing disk: $slow_disk"
        clear_disk $(get_disk $slow_disk)
        sleep 1s
        slow_disk_list="$slow_disk_list $slow_disk"
    done
    sleep 1s

    raid_type="raidz"
    [ $(howmany "$slow_disk_list") -eq 1 ] && raid_type=""
    [ $(howmany "$slow_disk_list") -gt 6 ] && raid_type="raidz2"

    echo "  raid_type=$raid_type"

    eval "zpool create -f \
        -o ashift=12 \
        -O atime=off \
        -O compression=lz4 \
        -O mountpoint=none \
        $SLOW_STORAGE_POOL $raid_type $slow_disk_list"
fi

systemctl enable /opt/server/systemd/system/disk-scrub.service
systemctl enable /opt/server/systemd/system/disk-scrub.timer

set_version $version ${0##*/}
exit 0
