#!/usr/bin/env bash

. ${SERVER_INSTALL:-/opt}/server/include

version=1

echo "Starting ${0##*/} patch on pid $$."
check_pid ${0##*/} $$ && exit 0
check_version $version ${0##*/} && exit 0

patch_requires "apt" 1
errorcheck && exit 1

apt-get install -qq --no-install-recommends zfs-initramfs
errorcheck && echoerr "error installing zfs-initramfs" && exit 1

fast_storage_enabled=$(get_server_setting "fast-storage-enabled")
fast_storage_enabled=${fast_storage_enabled:-0}
fast_disks=$(get_server_setting "fast-disks")
fast_disks=${fast_disks:-0}
slow_storage_enabled=$(get_server_setting "slow-storage-enabled")
slow_storage_enabled=${slow_storage_enabled:-0}
slow_disks=$(get_server_setting "slow-disks")
slow_disks=${slow_disks:-0}

if ! zpool status $FAST_STORAGE_POOL >/dev/null 2>&1 && \
    [ $fast_storage_enabled -eq 1 ] && \
    [ ! -z $fast_disks ]
then
    fast_disk_list=
    for fast_disk in $fast_disks; do
        echo "clearing disk: $fast_disk"
        clear_disk $fast_disk
        sleep 1s
        fast_disk_list="$fast_disk_list $(get_disk_link $fast_disk)"
    done
    sleep 1s

    raid_type="mirror"
    [ $(howmany $fast_disk_list) -eq 1 ] && raid_type=""
    [ $(howmany $fast_disk_list) -gt 3 ] && raid_type="raidz"

    eval "zpool create -f \
        -o ashift=13 \
        -O atime=off \
        -O compression=lz4 \
        -O mountpoint=/mnt \
        -O canmount=off \
        $FAST_STORAGE_POOL $raid_type $fast_disk_list"
    errorcheck && echoerr "error creating fast storage pool" && return 1

    ! zfs list | grep "$FAST_STORAGE_POOL/var" && \
        zfs create -o mountpoint=legacy $FAST_STORAGE_POOL/var

    ! cat /etc/fstab | grep " /var " && \
        echo "$FAST_STORAGE_POOL/var /var zfs defaults,x-systemd.requires=zfs-mount.service 0 0" >> /etc/fstab
    ! mount | grep " /var " && mount /var
fi

if ! zpool status $SLOW_STORAGE_POOL >/dev/null 2>&1 && \
    [ $slow_storage_enabled -eq 1 ] && \
    [ ! -z $slow_disks ]
then
    slow_disk_list=
    echo "clearing all storage disks"
    for slow_disk in $slow_disks; do
        echo "clearing disk: $slow_disk"
        clear_disk $slow_disk
        sleep 1s
        slow_disk_list="$slow_disk_list $(get_disk_link $slow_disk)"
    done
    sleep 1s
    echo "creating storage pool"

    raid_type="raidz"
    [ $(howmany $slow_disk_list) -eq 1 ] && raid_type=""
    [ $(howmany $slow_disk_list) -gt 6 ] && raid_type="raidz2"

    eval "zpool create -f \
        -o ashift=12 \
        -O atime=off \
        -O compression=lz4 \
        -O mountpoint=/mnt \
        $SLOW_STORAGE_POOL $raid_type $slow_disk_list"
    errorcheck && echoerr "error creating storage pool" && return 1
fi

set_version $version ${0##*/}
echo "Completed ${0##*/} patch on pid $$."
exit 0
! cat /etc/fstab | grep " /var " && \
    echo "$FAST_STORAGE_POOL/var /var zfs defaults,x-systemd.requires=zfs-mount.service 0 0" >> /etc/fstab
! mount | grep " /var " && mount /var