#!/usr/bin/env bash

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=1

echo "Starting ${0##*/} patch on pid $$."
check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

rm "/etc/rsyslog.d/"*
echo "*.* @$SYSLOG_ADDRESS:$SYSLOG_PORT" > "/etc/rsyslog.d/50-default.conf"

set_version $version ${0##*/}
echo "Completed ${0##*/} patch on pid $$."
exit 0
