#!/usr/bin/env bash

set -e

export DEBIAN_FRONTEND=noninteractive
SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=0

check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

echo "setting syslog to remote host $SYSLOG_ADDRESS:$SYSLOG_PORT"
rm "/etc/rsyslog.d/"*
echo "*.* @$SYSLOG_ADDRESS:$SYSLOG_PORT" > "/etc/rsyslog.d/50-default.conf"

set_version $version ${0##*/}
exit 0
