#!/usr/bin/env bash

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=1

check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

ln -s /usr/share/zoneinfo/$SERVER_TIMEZONE /etc/localtime
echo $SERVER_TIMEZONE > /etc/timezone

set_version $version ${0##*/}
exit 0
