version: "3.7"
services:
  zwave:
    container_name: zwave
    restart: always
    # ports:
    #   - "3000:3000"
    networks:
      - proxy
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mysupersecretkey
      - TZ=America/Chicago
    devices:
      - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
    volumes:
      - '$STORAGE_CONFIG_DIR/zwave:/usr/src/app/store'
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.zwave.loadbalancer.server.port=8091"
      - "traefik.http.routers.zwave-local.service=zwave"
      - "traefik.http.routers.zwave-local.entryPoints=web"
      - "traefik.http.routers.zwave-local.rule=Host(`zwave.$SERVER_DOMAIN`)"
      - "traefik.http.routers.zwave-local.middlewares=local-only@file"
      - "traefik.http.routers.zwave-secure.entryPoints=websecure"
      - "traefik.http.routers.zwave-secure.rule=Host(`zwave.$SERVER_DOMAIN`)"
      - "traefik.http.routers.zwave-secure.middlewares=oauth@file"
      - "traefik.http.routers.zwave-secure.tls=true"
      - "traefik.http.routers.zwave-secure.tls.certresolver=leresolver"
      - "traefik.http.routers.zwave-secure.service=zwave"
    image: zwavejs/zwavejs2mqtt:latest

networks:
  proxy:
    external: true