version: '3'
services:
  nzbget:
    image: crazymanjinn/zfswatcher
    hostname: zfswatcher
    domainname: ${SERVER_DOMAIN}
    logging:
      driver: syslog
      options:
        syslog-address: udp://${SYSLOG_ADDRESS}:${SYSLOG_PORT}
