#!/usr/bin/env bash

# Declare array of services and pretty human readable names
declare -a services=(
"systemd-networkd"
"systemd-resolved"
"rsyslog"
"ssh"
"docker"
"media-services"
)
declare -a serviceName=(
"Networking"
"DNS Resolver"
"Syslog"
"SSH"
"Docker"
"Media Services"
)
declare -a serviceStatus=()

# Get status of all my services
for service in "${services[@]}"
do
    serviceStatus+=($(systemctl is-active "$service.service"))
done

width=120
line="  "
lineLen=0

echo ""
echo "Services running:"

for i in ${!serviceStatus[@]}
do
    # Color the next line green if it's active, else red
    if [ "${serviceStatus[$i]}" == "active" ]; then
	echo -e "  ${serviceName[$i]}: \e[32m● Active\e[0m"
    else
	echo -e "  ${serviceName[$i]}: \e[31m▲ Failed\e[0m"
    fi
done