#!/usr/bin/env bash

# Declare array of services and pretty human readable names
declare -a services=(
"systemd-networkd"
"systemd-resolved"
"rsyslog"
"ssh"
"docker"
"docker-compose@download"
"docker-compose@plex"
)
declare -a serviceName=(
"Networking"
"DNS Resolver"
"Syslog"
"SSH"
"Docker"
"Download Services"
"Plex Services"
)
declare -a serviceStatus=()

# Get status of all my services
for service in "${services[@]}"
do
    serviceStatus+=($(systemctl is-active "$service.service"))
done

width=120
line="  "
lineLen=0

echo ""
echo "Services running:"

for i in ${!serviceStatus[@]}
do
    # Next line and next line length
    next=" ${serviceName[$i]}: \e[5m${serviceStatus[$i]}"
    nextLen=$((1+${#next}))

    # If the current line will exceed the max column with then echo the current line and start a new line
    if [[ $((lineLen+nextLen)) -gt width ]]; then
	echo -e "$line"
	lineLen=0
	line="  "
    fi

    lineLen=$((lineLen+nextLen))

    # Color the next line green if it's active, else red
    if [[ "${serviceStatus[$i]}" == "active" ]]; then
	line+="${serviceName[$i]}: \e[32m● ${serviceStatus[$i]}\e[0m "
    else
	line+="${serviceName[$i]}: \e[31m▲ ${serviceStatus[$i]}\e[0m "
    fi
done

# echo what is left
echo -e "$line"