#!/usr/bin/env bash

echo -e "\nPool status"

for pool in $(zpool list -H -o name)
do
    used=$(zfs list -H -o used $pool)
    used_bites=$(df | grep $pool | awk '{print $3}')
    available=$(zfs list -H -o avail $pool)
    available_bites=$(df | grep $pool | awk '{print $4}')
    percent=$((70*used_bites/available_bites))
    line="[\e[42m" #green
    [ $percent -gt 50 ] && line="[\e[43m" #yellow
    [ $percent -gt 68 ] && line="[\e[41m" #red
    i=0
    while [ $i -lt $percent ]
    do
        line+=" "
        i=$((i+1))
    done
    line+="\e[49m"
    while [ $i -lt 70 ]
    do
        line+=" "
        i=$((i+1))
    done
    line+="]"

    echo -e "  $pool: $([ "$(zpool status -x $pool)" == "pool '$pool' is healthy" ] && echo "\e[32mHEALTHY\e[0m" || echo "\e[31mUNHEALTHY\e[0m" )
    used: $used  |  available: $available
$line"
done