#!/usr/bin/env bash

set -o errexit
set -o nounset

source ~/server/scripts/setup/system/clean_disk
source ~/server/scripts/setup/zfs/zroot_pool
source ~/server/scripts/setup/zfs/zroot_datasets
source ~/server/scripts/setup/zfs/zfast_pool
source ~/server/scripts/setup/zfs/zfast_datasets
source ~/server/scripts/setup/zfs/zstorage_pool
source ~/server/scripts/setup/zfs/zstorage_datasets
source ~/server/scripts/setup/zfs/extra_datasets

function zfs_init {

if zpool list zfast >/dev/null 2>&1
then
    echo "    zfast already exists - destroying!"
    zpool destroy -f zfast >/dev/null 2>&1
fi
if zpool list zroot >/dev/null 2>&1
then
    echo "    zroot already exists - destroying!"
    zpool destroy -f zroot >/dev/null 2>&1
fi

for disk in ${root_drive_list} ${fast_drive_list}
do
    echo "    Cleaning ${disk}..."
    clean_disk $disk
done

echo "  --Starting ZFS setup."

zroot_pool
zroot_datasets
zfast_pool
zfast_datasets
zstorage_pool
zstorage_datasets
extra_datasets

echo "  --ZFS setup complete."

return 0

}
