#!/usr/bin/env bash

set -e

export DEBIAN_FRONTEND=noninteractive
SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"
. "$SERVER_INSTALL/include"

version=0

check_version $version ${0##*/} && echo "patch ${0##*/} already on latest version." && exit 0

password=$(get_server_setting "password")
[ -z $password ] && echoerr "password not set" && exit 1

echo "creating admin user/group"
groupadd -g $ADMIN_GROUP_ID $ADMIN_USERNAME
groupadd -g $DOCKER_PGID docker_group
useradd -m -u $ADMIN_USER_ID -g $ADMIN_USERNAME \
    -G plugdev,sudo,docker_group -s /bin/bash $ADMIN_USERNAME
useradd -r -u $DOCKER_PUID -g docker_group -s /sbin/nologin docker_user
echo "setting password"
echo "$ADMIN_USERNAME:$passwrd" | chpasswd

set_version $version ${0##*/}
exit 0
