#!/usr/bin/env bash

echo -e "\nPool status"

width=70

for pool in $(zpool list -H -o name)
do
    used=$(cat /etc/server/motd/$pool/info | grep used | head -1 | cut -d "=" -f2)
    used_bites=$(cat /etc/server/motd/$pool/info | grep used_bites | head -1 | cut -d "=" -f2)
    available=$(cat /etc/server/motd/$pool/info | grep available | head -1 | cut -d "=" -f2)
    available_bites=$(cat /etc/server/motd/$pool/info | grep available_bites | head -1 | cut -d "=" -f2)
    total=$(cat /etc/server/motd/$pool/info | grep total | head -1 | cut -d "=" -f2)
    total_bites=$(cat /etc/server/motd/$pool/info | grep total_bites | head -1 | cut -d "=" -f2)
    percent=$((width*used_bites/total_bites))
    line="[\e[42m" #green
    [ $percent -gt 50 ] && line="[\e[43m" #yellow
    [ $percent -gt 68 ] && line="[\e[41m" #red
    i=0
    while [ $i -lt $percent ]
    do
        line+=" "
        i=$((i+1))
    done
    line+="\e[49m"
    while [ $i -lt $width ]
    do
        line+=" "
        i=$((i+1))
    done
    line+="\e[0m]"

    echo -e "  $pool: $([ "$(zpool status -x $pool)" == "pool '$pool' is healthy" ] && echo "\e[32mHEALTHY\e[0m" || echo "\e[31mUNHEALTHY\e[0m" )
    available: $available  |  used: $used  |  total: $total
$line"
    for disk_file in /etc/server/motd/$pool/disks/*
    do
        disk=${disk_file##*/}
        disk_link="/dev/disk/by-id/$disk"
        temp=$(cat /etc/server/motd/$pool/disks/$disk/info | grep temp | head -1 | cut -d "=" -f2)
        if [ $temp -gt 40 ]; then
            color_start="\e[33m"
            [ $temp -gt 55 ] && color_start="\e[31m"
            echo "        $disk"
            echo -e "            Temperature: $color_start$temp°C\e[0m"
        fi
    done
    echo " "
done
