http:
  middlewares:
    https-headers:
      headers:
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 315360000
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
