http:
  routers:
    drive:
      entryPoints:
        - web
      rule: "Host(`drive.flanneryonline.com`)"
      middlewares:
        - https-redirect
      service: drive
    drive-secure:
      entryPoints:
        - websecure
      rule: "Host(`drive.flanneryonline.com`)"
      middlewares:
       - internal-auth
      tls:
        certResolver: leresolver
      service: drive
  services:
    drive:
      loadBalancer:
        servers:
          - url: "http://server-nas.flanneryonline.com:5000"
