http:
  routers:
    storage:
      entryPoints:
        - web
      middlewares:
        - https-redirect@file
      service: storage
    storage-secure:
      entryPoints:
        - websecure
      rule: Host('storage.flanneryonline.com')
      # middlewares:
      #   - storage
      tls:
        certResolver: leresolver
      service: storage
  services:
    storage:
      loadBalancer:
        servers:
          - url: http://10.10.10.1:8006
# middlewares:
#   storage:
#     headers:
#       frameDeny: true
#       sslRedirect: true
#       browserXssFilter: true
#       contentTypeNosniff: true
#       forceSTSHeader: true
#       stsIncludeSubdomains: true
#       stsPreload: true