http:
  routers:
    ns:
      entryPoints:
        - web
      rule: "Host(`ns.flanneryonline.com`)"
      middlewares:
        - https-redirect
      service: ns
    ns-secure:
      entryPoints:
        - websecure
      rule: "Host(`ns.flanneryonline.com`)"
      middlewares:
        - ns
        - oauth
      tls:
        certResolver: leresolver
      service: ns
  services:
    ns:
      loadBalancer:
        servers:
          - url: "http://pi.hole:80"
  middlewares:
    ns:
      addPrefix:
        prefix: "/admin"
