http:
  routers:
    home:
      entryPoints:
        - web
      middlewares:
        - https-redirect@file
      service: home
    home-secure:
      entryPoints:
        - websecure
      rule: Host('home.flanneryonline.com')
      # middlewares:
      #   - home
      tls:
        certResolver: leresolver
      service: home
  services:
    home:
      loadBalancer:
        servers:
          - url: http://homeassistant.flanneryonline.com:8123
# middlewares:
#   home:
#     headers:
#       frameDeny: true
#       sslRedirect: true
#       browserXssFilter: true
#       contentTypeNosniff: true
#       forceSTSHeader: true
#       stsIncludeSubdomains: true
#       stsPreload: true