http:
  routers:
    password:
      entryPoints:
        - web
      rule: "Host(`password.flanneryonline.com`)"
      middlewares:
        - https-redirect
      service: password
    password-secure:
      entryPoints:
        - websecure
      rule: "Host(`password.flanneryonline.com`)"
      middlewares:
       - internal-auth
      tls:
        certResolver: leresolver
      service: password
  services:
    password:
      loadBalancer:
        servers:
          - url: "http://services.flanneryonline.com:80"
