http:
  routers:
    ns:
      entryPoints:
        - web
      middlewares:
        - https-redirect@file
      service: ns
    ns-secure:
      entryPoints:
        - websecure
      rule: Host(`ns.flanneryonline.com`)
      middlewares:
        - ns
      tls:
        certResolver: leresolver
      service: ns
  services:
    ns:
      loadBalancer:
        servers:
          - url: http://pi.hole:80
  middlewares:
    ns:
      addPrefix:
        prefix: "/admin"