http:
  routers:
    nas:
      entryPoints:
        - web
      middlewares:
        - https-redirect@file
      rule: "Host(`nas.flanneryonline.com`)"
      service: nas
    nas-secure:
      entryPoints:
        - websecure
      rule: "Host(`nas.flanneryonline.com`)"
      tls:
        certResolver: leresolver
      service: nas
  services:
    nas:
      loadBalancer:
        servers:
          - url: "http://server-nas.flanneryonline.com:5000"
