http:
  routers:
    storage:
      entryPoints:
        - web
      middlewares:
        - https-redirect@file
      service: storage
    storage-secure:
      entryPoints:
        - websecure
      rule: "Host(`storage.flanneryonline.com`)"
      tls:
        certResolver: leresolver
      service: storage
  services:
    storage:
      loadBalancer:
        servers:
          - url: "http://10.10.10.1:8006"
