http:
  routers:
    router:
      entryPoints:
        - "http"
      middlewares:
        - https-redirect@file
      service: router
    router-secure:
      entryPoints:
        - "https"
      rule: "Host('router.flanneryonline.com')"
      # middlewares:
      #   - router
      tls:
        certResolver: leresolver
      service: router
  services:
    router:
      loadBalancer:
        servers:
          - url: "http://10.0.0.1:8888"
# middlewares:
#   router:
#     headers:
#       frameDeny: true
#       sslRedirect: true
#       browserXssFilter: true
#       contentTypeNosniff: true
#       forceSTSHeader: true
#       stsIncludeSubdomains: true
#       stsPreload: true