http:
  routers:
    router:
      entryPoints:
        - web
      middlewares:
        - https-redirect@file
      rule: "Host(`router.flanneryonline.com`)"
    router-secure:
      entryPoints:
        - websecure
      rule: "Host(`router.flanneryonline.com`)"
      tls:
        certResolver: leresolver
      service: router
  services:
    router:
      loadBalancer:
        servers:
          - url: "http://10.0.0.1:8888"
