#!/bin/sh

set -o errexit
set -o nounset

for f in ~/server/include/software/installs/*
do
   . $f
done

software_setup () {

    local altroot=${1:-${ALTROOT:-${altroot:-}}}

    for fa in `ls -A ~/server/include/software/installs/`
    do 
        eval "${fa}_install"
    done

    return 0
}
