#!/usr/bin/env bash

set -o errexit
set -o nounset

function user_init {

local altroot=${1:-${ALTROOT:-${altroot:-}}}

echo "defaultpasswd=no" > "${altroot}/etc/pw.conf"
echo "reuseuids=yes" >> "${altroot}/etc/pw.conf"
echo "reusegids=yes" >> "${altroot}/etc/pw.conf"
echo "nispasswd=" >> "${altroot}/etc/pw.conf"
echo "skeleton=/usr/share/skel" >> "${altroot}/etc/pw.conf"
echo "#newmail=" >> "${altroot}/etc/pw.conf"
echo "logfile=no" >> "${altroot}/etc/pw.conf"
echo "home=/usr/home" >> "${altroot}/etc/pw.conf"
echo "#homemode=" >> "${altroot}/etc/pw.conf"
echo "#shellpath=" >> "${altroot}/etc/pw.conf"
echo "#shells=" >> "${altroot}/etc/pw.conf"
echo "defaultshell=/bin/sh" >> "${altroot}/etc/pw.conf"
echo "defaultgroup=no" >> "${altroot}/etc/pw.conf"
echo "#extragroups=" >> "${altroot}/etc/pw.conf"
echo "defaultclass=no" >> "${altroot}/etc/pw.conf"
echo "#minuid=1000" >> "${altroot}/etc/pw.conf"
echo "#maxuid=32000" >> "${altroot}/etc/pw.conf"
echo "#mingid=1000" >> "${altroot}/etc/pw.conf"
echo "#maxgid=32000" >> "${altroot}/etc/pw.conf"
echo "expire_days=0" >> "${altroot}/etc/pw.conf"
echo "password_days=0" >> "${altroot}/etc/pw.conf"

echo "    pw.conf created"

pw -R "${altroot}" useradd -n "media" -u 1001 -s "/usr/sbin/nologin" -d "/nonexistent" -w no
pw -R "${altroot}" useradd -n "homeadmin" -u 5000 -s "/usr/local/bin/zsh" -G "wheel, media" -w no
chroot "${altroot}" passwd "root"
chroot "${altroot}" passwd "homeadmin"

echo "    Copying configs from git."
chroot "${altroot}" su homeadmin -c "[ ! -d /usr/home/homeadmin ] && mkdir -p /usr/home/homeadmin"
chroot "${altroot}" su homeadmin -c "cd /usr/home/homeadmin && /usr/local/sbin/git clone https://github.com/flanneryonline/dotfiles >/dev/null"
chroot "${altroot}" su homeadmin -c "cd /usr/home/homeadmin && /usr/local/sbin/git clone https://github.com/flanneryonline/server >/dev/null"
chroot "${altroot}" su homeadmin -c "chmod +x /usr/home/homeadmin/dotfiles/dot.sh"
chroot "${altroot}" su homeadmin -c "/usr/home/homeadmin/dotfiles/dot.sh >/dev/null"
chroot "${altroot}" su homeadmin -c "vim +PlugInstall +qall >/dev/null 2>&1"

echo "    users created"
return 0
}
