#!/bin/sh

set -o errexit
set -o nounset

ssmtp_conf_init () {

    local altroot=${1:-${ALTROOT:-${altroot:-}}}

    if [ ! -d "${altroot}/usr/local/etc/ssmtp" ] ; then mkdir -p "${altroot}/usr/local/etc/ssmtp"; fi
    echo "root=pat@flanneryonline.com" > "${altroot}/usr/local/etc/ssmtp/ssmtp.conf"
    echo "mailhub=smtp.mail.wowway.com" >> "${altroot}/usr/local/etc/ssmtp/ssmtp.conf"
    echo "rewriteDomain=flanneryonline.com" >> "${altroot}/usr/local/etc/ssmtp/ssmtp.conf"
    echo "AuthUser=pflannery" >> "${altroot}/usr/local/etc/ssmtp/ssmtp.conf"
    echo "root:pat@flanneryonline.com" > "${altroot}/usr/local/etc/ssmtp/revaliases"
    echo "homeadmin:pat@flanneryonline.com" > "${altroot}/usr/local/etc/ssmtp/revaliases"
    chroot "${altroot}" /usr/bin/make -C "${base_port_dir:-"/usr/ports"}/mail/ssmtp" replace

    return 0
}
