#!/bin/sh

set -o errexit
set -o nounset

. ~/server/scripts/setup/jail/base
. ~/server/scripts/setup/jail/staging
. ~/server/scripts/setup/jail/fstab_init

jail_create () {

    local jail_name=${1:-}
    local jail_release=${2:-}
    local jail_zfs=${JAIL_ZFS:-${jail_zfs:-"zfast/jails"}}
    local altroot=${ALTROOT:-${altroot:-}}
    local jail_dir=${JAIL_DIR:-${jail_dir:-"${altroot}/usr/local/jails"}}

    #check variables
    if [ -z "${jail_name// }" ]
    then
        echo >&2 "****Failed to create jail. Name must not be blank.****"
        return 1
    fi
    if [ -z "${jail_release// }" ]
    then
        echo >&2 "****Failed to create jail. Release must not be blank.****"
        return 1
    fi

    if [ ! -d "${jail_dir}/mount/${jail_name}" ]
    then
        mkdir -p "${jail_dir}/mount/${jail_name}"
    fi

    jail_base ${jail_release}
    jail_staging ${jail_release}
    jail_fstab_init ${jail_name} ${jail_release}
    zfs clone "${jail_zfs}/staging/${jail_release}@skeleton" "${jail_zfs}/thinjails/${jail_name}"

    echo "    ${jail_name} created."
    return 0
}
