#!/bin/sh

set -o errexit
set -o nounset

. ~/server/include/jail/etc/jail_conf_init
. ~/server/include/jail/base
. ~/server/include/jail/staging

jail_init () {}
    jail_base
    jail_staging
    jail_conf_init
    sysrc -R "${altroot}" jail_enable="YES" >/dev/null 2>&1
}
