#!/usr/bin/env bash

set -e

docker create \
--name=dotnetcore \
--health-cmd="echo '' >/dev/null" \
--health-interval=5s \
--health-start-period=5s \
--health-timeout=2s \
flanneryonline/dotnetcore-test