#!/usr/bin/env bash

set -e

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"

docker create \
--name=emby \
-p 8096:8096 \
-p 8920:8920 \
--health-cmd="curl -sSf 'http://localhost:8096' >/dev/null" \
--health-interval=5s \
--health-start-period=15s \
--health-timeout=2s \
-e UID=$DOCKER_PUID -e GID=$DOCKER_PGID \
-e TZ=$SERVER_TIMEZONE \
-v $STORAGE_CONFIG_DIR/emby:/config \
-v $STORAGE_MEDIA_DIR:/media \
emby/embyserver
