#!/usr/bin/env bash

set -e

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"

docker create \
--name=mysql \
--health-cmd="mysqladmin ping -h 127.0.0.1' >/dev/null" \
--health-interval=5s \
--health-start-period=5s \
--health-timeout=2s \
-v $STORAGE_CONFIG_DIR/mysql:/var/lib/mysql \
mysql/mysql-server