#!/usr/bin/env bash

set -e

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"

docker create \
--name=ombi \
-p 3579:3579 \
--health-cmd="curl -sSf 'http://127.0.0.1:3579' >/dev/null" \
--health-interval=5s \
--health-start-period=5s \
--health-timeout=2s \
-e PUID=$DOCKER_PUID -e PGID=$DOCKER_PGID \
-e TZ=$SERVER_TIMEZONE \
-v $STORAGE_CONFIG_DIR/ombi:/config \
linuxserver/ombi