#!/usr/bin/env bash

set -e

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"

docker pull dperson/samba

docker create -t \
--name=samba \
-p 139:139 \
-p 445:445 \
-e TZ=$SERVER_TIMEZONE \
-v $STORAGE_CONFIG_DIR:/mnt/configs \
-v $STORAGE_DOWNLOAD_DIR:/mnt/downloads \
-v $STORAGE_MEDIA_DIR:/mnt/media \
-v $STORAGE_SHARE_DIR:/mnt/shares \
-v $STORAGE_CONFIG_DIR/samba:/config \
dperson/samba -r -I /config/include.conf