#!/usr/bin/env bash

set -e

SERVER_INSTALL=${SERVER_INSTALL:-/opt/server}
. "$SERVER_INSTALL/environment"

docker create \
--name=sonarr \
-p 8989:8989 \
--health-cmd="curl -sSf 'http://localhost:8989' >/dev/null" \
--health-interval=5s \
--health-start-period=5s \
--health-timeout=2s \
-e PUID=$DOCKER_PUID -e PGID=$DOCKER_PGID \
-e TZ=$SERVER_TIMEZONE \
-v $STORAGE_CONFIG_DIR/sonarr:/config \
-v $STORAGE_MEDIA_DIR/shows:/shows \
-v $STORAGE_DOWNLOAD_DIR:/downloads \
linuxserver/sonarr