version: '3'
services:
  plex:
    image: linuxserver/plex
    domainname: ${SERVER_DOMAIN}
    network_mode: host
    tmpfs: /transcode
    volumes:
      - ${STORAGE_CONFIG_DIR}/plex:/config
      - ${STORAGE_MEDIA_DIR}:/media
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${SERVER_TIMEZONE}
      - VERSION=latest
  tautulli:
    image: linuxserver/tautulli
    domainname: ${SERVER_DOMAIN}
    volumes:
      - ${STORAGE_CONFIG_DIR}/tautulli:/config
      - ${STORAGE_CONFIG_DIR}/plex:/logs:ro
    ports:
      - 8181:8181
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${SERVER_TIMEZONE}
  ombi:
    image: linuxserver/ombi
    domainname: ${SERVER_DOMAIN}
    volumes:
      - ${STORAGE_CONFIG_DIR}/ombi:/config
    ports:
      - 3579:3579
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${SERVER_TIMEZONE}
  pia:
    image: dperson/openvpn-client
    command: -r 10.0.0.0/8 -f "" -d
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 6789:6789       #nzbget
      - 8112:8112       #deluge
      - 58846:58846     #deluge
      - 58946:58946     #deluge
      - 58946:58946/udp #deluge
      - 5075:5075       #hydra
      - 9117:9117       #jackett
    tmpfs:
      - /tmp
    security_opt:
      - label:disable
    domainname: ${SERVER_DOMAIN}
    volumes:
      - ${STORAGE_CONFIG_DIR}/pia:/vpn
    environment:
      - REGION=US Midwest
      - TZ=${SERVER_TIMEZONE}
  nzbget:
    image: linuxserver/nzbget
    depends_on:
      - pia
    network_mode: service:pia
    domainname: ${SERVER_DOMAIN}
    volumes:
      - ${STORAGE_CONFIG_DIR}/nzbget:/config
      - ${STORAGE_DOWNLOAD_DIR}:/downloads
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${SERVER_TIMEZONE}
  deluge:
    image: linuxserver/deluge
    depends_on:
      - pia
    network_mode: service:pia
    domainname: ${SERVER_DOMAIN}
    volumes:
      - ${STORAGE_CONFIG_DIR}/deluge:/config
      - ${STORAGE_DOWNLOAD_DIR}:/downloads
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${SERVER_TIMEZONE}
  hydra:
    image: linuxserver/hydra
    depends_on:
      - pia
    network_mode: service:pia
    domainname: ${SERVER_DOMAIN}
    volumes:
      - ${STORAGE_CONFIG_DIR}/hydra:/config
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${SERVER_TIMEZONE}
  jackett:
    image: linuxserver/jackett
    depends_on:
      - pia
    network_mode: service:pia
    domainname: ${SERVER_DOMAIN}
    volumes:
      - ${STORAGE_CONFIG_DIR}/jackett:/config
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${SERVER_TIMEZONE}
  sonarr:
    image: linuxserver/sonarr
    domainname: ${SERVER_DOMAIN}
    ports:
      - 8989:8989
    volumes:
      - ${STORAGE_CONFIG_DIR}/sonarr:/config
      - ${STORAGE_MEDIA_DIR}/shows:/shows
      - ${STORAGE_DOWNLOAD_DIR}:/downloads
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${SERVER_TIMEZONE}
  radarr:
    image: linuxserver/radarr
    domainname: ${SERVER_DOMAIN}
    ports:
      - 7878:7878
    volumes:
      - ${STORAGE_CONFIG_DIR}/radarr:/config
      - ${STORAGE_MEDIA_DIR}/movies:/movies
      - ${STORAGE_DOWNLOAD_DIR}:/downloads
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${SERVER_TIMEZONE}
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    domainname: ${SERVER_DOMAIN}
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${STORAGE_CONFIG_DIR}/portainer:/data
  watchtower:
    image: v2tec/watchtower
    command: --cleanup
    domainname: ${SERVER_DOMAIN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock