#!/bin/sh

set -o errexit

export ASSUME_ALWAYS_YES=yes
export HANDLE_RC_SCRIPTS=yes
export PAGER=cat

if ! pkg info -x 'pkg(-devel)?$'
then
    pkg bootstrap
fi

if ! pkg info -x 'pkg(-devel)?$'
then
    echo "****pkg init failed. bootstrap didn't work. Check pkg man pages for updates.****"
    exit 1
fi

pkg update
pkg upgrade
pkg autoremove
pkg audit -Fr
pkg clean -ay

if [ `sysctl -n security.jail.jailed` -eq 0 ]
then
    freebsd-update fetch
    freebsd-update install

    for i in /var/db/freebsd-update/files/*
    do 
        rm "$i"
    done

    portsnap auto
fi

exit 0
