#!/usr/bin/env bash

set -o errexit
set -o nounset

function zfast_pool {

local fast_drive_list=${fast_drive_list:-}
local fast_pool=${FAST_POOL:-${fast_pool:-"zfast"}}
local altroot=${ALTROOT:-${altroot:-}}

if [[ -z "${fast_drive_list// }" ]]
then
    echo "****Failed to setup zfast pool. fast_drive_list is not set.****"
    return 1
fi
if [[ -z "${altroot// }" ]]
then
    echo "****Failed to setup zfast pool. altroot is not set.****"
    return 1
fi

for check_drive in $fast_drive_list
do
    if ! ls "/dev/${check_drive}" >/dev/null
    then
        echo "****Failed to setup zfast pool. $check_drive is not a valid drive.****"
        return 1
    fi
done

echo "    Creating ZFS partitions on drive list: ${fast_drive_list}"
local drive_number=0
for fast_drive in ${fast_drive_list}
do
    gpart create -s gpt "${fast_drive}" >/dev/null
    gpart add -a 4k -t freebsd-zfs -l "fast${drive_number}" "${fast_drive}" >/dev/null
    gnop create -S 4096 "/dev/gpt/fast${drive_number}" >/dev/null
    local zpool_list="${zpool_list:-}${space:-}/dev/gpt/fast${drive_number}.nop"
    local space=" "
    ((drive_number = drive_number + 1))
done

echo "    Creating zfast pool at $altroot using cache at $zcache"
zpool create -f -m none -o altroot="${altroot}" -o cachefile="${zcache}" ${fast_pool} ${zpool_list} >/dev/null

echo "    ZFS re-import to set ashift=12 using gnop trick"
zpool export ${fast_pool}
for gpt_nop in /dev/gpt/fast*.nop
do
    gnop destroy "${gpt_nop}" >/dev/null
done
zpool import -o altroot="${altroot}" -o cachefile="${zcache}" ${fast_pool}

echo "    setting ZFS flags"
zfs set compression=lz4 ${fast_pool}
zfs set atime=off ${fast_pool}

echo "    Fast drive ZFS setup complete."
return 0
}
