#!/usr/bin/env bash

set -o errexit
set -o nounset

function clean_disk {

# No args? More than 1 arg?
if [[ $# -ne 1 ]]
then
    exit 1
fi

drive=$1

# Check if arg is a drive
if [[ ! -e /dev/${drive} ]]
then 
    exit 1
fi

# max is the number of partitions that need to be removed before we can destroy the disk
max=$(gpart show ${drive} | awk '{if ($3>0 && $3<128){max=$3}} END{print max}')
if [[ "${max}" =~ "[^0-9]+" ]]
then
    max=0
fi
while [[ ${max} > 0 ]]
do
    gpart delete -i ${max} "${drive}"
    ((max--))
done
gpart destroy "${drive}"

return 0

}
