#!/usr/bin/env bash

set -o errexit
set -o nounset

source ~/server/scripts/setup/setup_clean_disk
source ~/server/scripts/setup/setup_zfs_zroot_pool
source ~/server/scripts/setup/setup_zfs_zroot_datasets
source ~/server/scripts/setup/setup_zfs_zfast_pool
source ~/server/scripts/setup/setup_zfs_zfast_datasets
source ~/server/scripts/setup/setup_zfs_zstorage_pool
source ~/server/scripts/setup/setup_zfs_zstorage_datasets
source ~/server/scripts/setup/setup_zfs_extra_datasets

function zfs_init {

echo "WARNING: The following disks will be DELETED!!!"
for disk in "${root_drive_list} ${fast_drive_list}"
do
    echo "${disk}"
done

echo "Press any key to continue. (Ctrl-C to exit)"
read -n 1 -s

for disk in "${root_drive_list} ${fast_drive_list}"
do
    clean_disk $disk
done

zfs_zroot_pool 
zfs_zroot_datasets
zfs_zfast_pool
zfs_zfast_datasets
zfs_zstorage_pool
zfs_zstorage_datasets
zfs_extra_datasets

return 0

}
