#!/usr/bin/env bash
# 
# This script assumes the list of drives provided have been wiped already.
#

set -o errexit
set -o nounset

function zfs_zroot_pool {

if [[ $# -eq 0 ]]
then
    echo "No drive list provided. Nothing changed."
    return 1
fi

local altroot=$1
local root_drive_list=$2

for check_drive in $root_drive_list
do
    if [[ ! ls "/dev/${check_drive}" ]]
    then
        return 1
    fi
done

echo "Creating zfs boot (512k) and a zfs root partitions on drive list: ${root_drive_list}"
local drive_number=0
for root_drive in $root_drive_list
do
    gpart create -s gpt "${root_drive}"
    gpart add -a 4k -s 512k -t freebsd-boot "${root_drive}"
    gpart add -a 4k -t freebsd-zfs -l "boot${drive_number}" "${root_drive}"
    gpart bootcode -b /boot/pmbr -p /boot/gptzfsboot -i 1 "${root_drive}"
    gnop create -S 4096 "/dev/gpt/boot${drive_number}"
    local zpool_list="${zpool_list:-}${space:-}/dev/gpt/boot${drive_number}.nop"
    local space=" "
    ((drive_number++))
done

zpool create -f -m none -o altroot="${altroot}" -o cachefile="${ZCACHE}" zroot mirror "${zpool_list}"
zfs set compression=lz4 zroot
zfs set atime=off zroot

return 0

}

