#!/usr/bin/env bash

set -o errexit
set -o nounset

source ~/server/scripts/setup/setup_system_install

function jail_base {

local jail_release=${1:-""}
if [[ "${jail_release}" == "" ]]
    echo "failed to create jail base. jail release not passed to jail_base."
    return 1
fi

jail_dir=${jail_dir:-""}
if [[ "${jail_dir}" == "" ]]
    echo "failed to create jail base. jail dir not set."
    return 1
fi

#make sure directory exists
mkdir -p "${jail_dir}/releases/${jail_release}"

#install system (no kernel)
system_install "${jail_dir}/releases/${jail_release}"

echo "Setting up base jail directory structure."
mkdir -p "${jail_dir}/skeleton/${jail_release}/home"
mkdir -p "${jail_dir}/skeleton/${jail_release}/portsbuild"
mkdir -p "${jail_dir}/releases/${jail_release}/skeleton"

mv "${jail_dir}/releases/${jail_release}/etc" "${jail_dir}/skeleton/${jail_release}/etc"
mv "${jail_dir}/releases/${jail_release}/usr/local" "${jail_dir}/skeleton/${jail_release}/usr/local"
mv "${jail_dir}/releases/${jail_release}/tmp" "${jail_dir}/skeleton/${jail_release}/tmp"
mv "${jail_dir}/releases/${jail_release}/var" "${jail_dir}/skeleton/${jail_release}/var"
mv "${jail_dir}/releases/${jail_release}/root" "${jail_dir}/skeleton/${jail_release}/root"

cp "${altroot}/usr/local/etc/portmaster.rc" "${jail_dir}/skeleton/${jail_release}/usr/local/etc/portmaster.rc"
cp "${altroot}/etc/resolv.conf" "${jail_dir}/skeleton/${jail_release}/etc/resolv.conf"
cp "${altroot}/etc/make.conf" "${jail_dir}/skeleton/${jail_release}/etc/make.conf"
echo "WRKDIRPREFIX?=/skeleton/portbuild" >> "${jail_dir}/skeleton/${jail_release}/etc/make.conf"

chroot "${jail_dir}/releases/${jail_release}" ln -s "skeleton/etc" "etc"
chroot "${jail_dir}/releases/${jail_release}" ln -s "skeleton/home" "home"
chroot "${jail_dir}/releases/${jail_release}" ln -s "skeleton/root" "root"
chroot "${jail_dir}/releases/${jail_release}" ln -s "../skeleton/usr/local" "usr/local"
chroot "${jail_dir}/releases/${jail_release}" ln -s "skeleton/tmp" "tmp"
chroot "${jail_dir}/releases/${jail_release}" ln -s "skeleton/var" "var"
chroot "${jail_dir}/releases/${jail_release}" ln -s "../../skeleton/usr/ports/distfiles" "usr/ports/distfiles"

sysrc -r "${jail_dir}/releases/${jail_release}" sendmail_enable="NO"
sysrc -r "${jail_dir}/releases/${jail_release}" sendmail_submit_enable="NO"
sysrc -r "${jail_dir}/releases/${jail_release}" sendmail_outbound_enable="NO"
sysrc -r "${jail_dir}/releases/${jail_release}" sendmail_msp_queue_enable="NO"

zfs snapshot "${jail_zfs}/skeleton/${jail_release}@skeleton"

echo "FreeBSD version ${jail_release} base jail created at ${jail_dir}"

return 0

}
