#!/usr/bin/env bash

set -o errexit
set -o nounset

function zfs_zfast_pool {

if [[ $# -eq 0 ]]
then
    echo "No drive list provided. Nothing changed."
    return 1
fi

local altroot=$1
local disk=$2

for check_drive in $root_drive_list
do
    if [[ ! ls "/dev/${check_drive}" ]]
    then
        return 1
    fi
done

gpart create -s gpt "${disk}"
gpart add -a 4k 0t freebsd-zfs -l "fast0" "${disk}"
gnop create -S 4096 /dev/gpt/fast0
zpool create -f -m none -o altroot="${altroot}" -o cachefile="${ZCACHE}" zfast /dev/gpt/fast0.nop
zfs set compression=lz4 zfast
zfs set atime=off zfast

return 0

}
