#!/usr/bin/env bash

set -o errexit
set -o nounset

function jail_config {

local jail_release=${1:-""}
if [[ "${jail_release}" == "" ]]
    echo "failed to create jail base. jail release not passed to jail_base."
    return 1
fi

jail_dir=${jail_dir:-""}
if [[ "${jail_dir}" == "" ]]
    echo "failed to create jail base. jail dir not set."
    return 1
fi

#check domain


#create jail.conf (overwrite)
echo "exec.start=\"/bin/sh /etc/rc\";"                       > "${jail_dir}/config/${jail_release}/jail.conf"
echo "exec.stop=\"/bin/sh /etc/rc.shutdown\";"              >> "${jail_dir}/config/${jail_release}/jail.conf"
echo "exec.clean;"                                          >> "${jail_dir}/config/${jail_release}/jail.conf"
echo "children.max=0;"                                      >> "${jail_dir}/config/${jail_release}/jail.conf"
echo "allow.set_hostname=0;"                                >> "${jail_dir}/config/${jail_release}/jail.conf"
echo "mount.devfs;"                                         >> "${jail_dir}/config/${jail_release}/jail.conf"
echo "allow.mount;"                                         >> "${jail_dir}/config/${jail_release}/jail.conf"
echo "allow.raw_sockets;"                                   >> "${jail_dir}/config/${jail_release}/jail.conf"
echo "interface=lagg0;"                                     >> "${jail_dir}/config/${jail_release}/jail.conf"
echo "path=\"${jail_dir}/mount/\${name}\";"                 >> "${jail_dir}/config/${jail_release}/jail.conf"
echo "host.hostname=\"\${name}server${t:-}.${domain}\";"    >> "${jail_dir}/config/${jail_release}/jail.conf"
echo "mount.fstab=\"${jail_dir}/config/${jail_release}/\${name}.fstab\";"   >> "${jail_dir}/config/${jail_release}/jail.conf"

ln -s "${jail_dir}/config/${jail_release}/jail.conf" "${altroot}/etc/jail.conf"

}
