#!/usr/bin/env bash

set -o errexit
set -o nounset

function pkg_init {

altroot=${altroot:-""}

if [[ "${altroot}" == "" ]]
    echo "pkg init failed. altroot not set."
    return 1
fi

#copied from man page
if \
    chroot "${altroot}" \
    TMPDIR=/dev/null \
    ASSUME_ALWAYS_YES=yes \
    PACKAGESITE=file:///nonexistent \
    pkg info -x 'pkg(-devel)?$' >/dev/null 2>&1
then
    env ASSUME_ALWAYS_YES=YES pkg bootstrap
fi

#make sure bootstrap worked
if \
    chroot "${altroot}" \
    TMPDIR=/dev/null \
    ASSUME_ALWAYS_YES=yes \
    PACKAGESITE=file:///nonexistent \
    pkg info -x 'pkg(-devel)?$' >/dev/null 2>&1
then
    echo "pkg init failed."
    return 1
fi

return 0

}
