version: "3"

services:

  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=NOREPLY@${SERVER_DOMAIN}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${ADMIN_EMAIL}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${EMAIL_SERVER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${EMAIL_USERNAME}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${EMAIL_PASSWORD}

  plex:
    image: linuxserver/plex
    volumes:
      - ${DOCKER_CONFIGS}/plex:/config
      - ${DOCKER_MEDIA}/shows:/data/tvshows
      - ${DOCKER_MEDIA}/movies:/data/movies
    ports:
      - 32400:32400
      - 32400:32400/udp
      - 32469:32469
      - 32469:32469/udp
      - 5353:5353/udp
      - 1900:1900/udp
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${SERVER_TIMEZONE}

  plexpy:
    image: linuxserver/plexpy
    depends_on:
      - plex
    volumes:
      - ${DOCKER_CONFIGS}/plexpy:/config
      - ${DOCKER_CONFIGS}/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports: 8181:8181
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${SERVER_TIMEZONE}

  ombi:
    image: linuxserver/ombi
    depends_on:
      - plex
    volumes:
      - ${DOCKER_CONFIGS}/ombi:/config
    ports: 3579:3579
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${SERVER_TIMEZONE}

  nzbget:
    image: linuxserver/nzbget
    volumes:
      - ${DOCKER_CONFIGS}/nzbget:/config
      - ${DOCKER_DOWNLOADS}/nzb:/downloads
      - ${DOCKER_DOWNLOADS}/complete:/downloads/complete
    ports:
      - 6789:6789
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${SERVER_TIMEZONE}

  sonarr:
    image: linuxserver/sonarr
    depends_on:
      - plex
      - nzbget
      - deluge
    volumes:
      - ${DOCKER_CONFIGS}/sonarr:/config
      - ${DOCKER_MEDIA}/shows:/shows
      - ${DOCKER_DOWNLOADS}/complete/shows:/downloads/complete
    ports:
      - 8989:8989
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${SERVER_TIMEZONE}

  deluge:
    image: linuxserver/deluge
    ports:
      - 8112:8112
      - 58846:58846
      - 58946:58946
      - 58946:58946/udp
    volumes:
      - ${DOCKER_CONFIGS}/deluge:/config
      - ${DOCKER_DOWNLOADS}/torrent:/downloads
      - ${DOCKER_DOWNLOADS}/complete:/downloads/complete
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${SERVER_TIMEZONE}

  radarr:
    image: linuxserver/radarr
    depends_on:
      - plex
      - nzbget
      - deluge
    volumes:
      - ${DOCKER_CONFIGS}/radarr:/config
      - ${DOCKER_MEDIA}/movies:/movies
      - ${DOCKER_DOWNLOADS}/complete/movies:/downloads/complete
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${SERVER_TIMEZONE}
    restart: always

  portainer:
    image: portainer/portainer
    networks:
      - proxy
    ports:
      - 9000:9000
    volumes:
      - ${DOCKER_CONFIGS}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nextcloud:
    image: linuxserver/nextcloud
      - mariadb
    networks:
      - database
      - proxy
    ports:
      - 443:443
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${SERVER_TIMEZONE}
    volumes:
      - ${DOCKER_CONFIGS}/nextcloud:/config
      - /storage:/data

  mariadb:
    image: linuxserver/mariadb
    networks:
      - database
    ports:
      - 3306:3306
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${SERVER_TIMEZONE}
      - MYSQL_ROOT_PASSWORD=mariadb
    volumes:
      - ${DOCKER_CONFIGS}/mariadb:/config