#!/usr/bin/env bash
# Arguments:
#   $1 = jail name
#   $2 = release

set -o errexit
set -o nounset

source ~/server/scripts/setup/jail/base

function jail_create {

local jail_name=${1:-""}
local jail_release=${2:-""}
local jail_zfs=${JAIL_ZFS:-${jail_zfs:-"zfast/jails"}}
local altroot=${ALTROOT:-${altroot:-""}}
local jail_dir=${JAIL_DIR:-${jail_dir:-"${altroot}/usr/local/jails"}}

#check variables
if [[ "${jail_name}" == "" ]]
then
    echo "Failed to create jail. Name must not be blank."
    return 1
fi
if [[ "${jail_release}" == "" ]]
then
    echo "Failed to create jail. Release must not be blank."
    return 1
fi

#make sure base release exists - create it if it does not
jail_base ${jail_release}

#clone skeleton
zfs clone "${jail_zfs}/staging/${jail_release}@skeleton" "${jail_zfs}/thinjails/${jail_name}"

#mount point
mkdir -p "${jail_dir}/mount/${jail_name}"

#jail fstab setup (overwrite)
echo "${jail_dir}/base/${release}           ${jail_dir}/mount/${jail_name}                  nullfs ro 0 0" >  "${jail_dir}/mount/${jail_name}.fstab"
echo "${jail_dir}/thinjails/${jail_name}    ${jail_dir}/mount/${jail_name}/skeleton         nullfs rw 0 0" >> "${jail_dir}/mount/${jail_name}.fstab"
echo "${data_dir}                           ${jail_dir}/mount/${jail_name}/mnt/data         nullfs rw 0 0" >> "${jail_dir}/mount/${jail_name}.fstab"
if [[ "${jail_name}" == "media" ]] || [[ "${jail_name}" == "download" ]] || [[ "${jail_name}" == "share" ]]
then
    echo "${media_dir}                      ${jail_dir}/mount/${jail_name}/mnt/media        nullfs rw 0 0" >> "${jail_dir}/mount/${jail_name}.fstab"
fi
if [[ "${jail_name}" == "download" ]] || [[ "${jail_name}" == "share" ]]
then
    echo "${download_dir}                   ${jail_dir}/mount/${jail_name}/mnt/downloads    nullfs rw 0 0" >> "${jail_dir}/mount/${jail_name}.fstab"
fi
if [[ "${jail_name}" == "share" ]]
then
    echo "${share_dir}                      ${jail_dir}/mount/${jail_name}/mnt/share        nullfs rw 0 0" >> "${jail_dir}/mount/${jail_name}.fstab"
fi
echo "${config_dir}                         ${jail_dir}/mount/${jail_name}/mnt/config       nullfs rw 0 0" >> "${jail_dir}/mount/${jail_name}.fstab"
echo "/usr/ports                            ${jail_dir}/mount/${jail_name}/usr/ports        nullfs ro 0 0" >> "${jail_dir}/mount/${jail_name}.fstab"

echo "    ${jail_name} created."

return 0
}
