#!/usr/bin/env bash

set -o errexit
set -o nounset

#web proxy
function jail_init_web {

local altroot=${ALTROOT:-${altroot:-""}}
local jail_dir=${JAIL_DIR:-${jail_dir:-"${altroot}/usr/local/jails"}}
jail_root="${jail_dir}/mount/web"
mount -F "${jail_dir}/mount/web.fstab"

chroot "${jail_root}" ASSUME_ALWAYS_YES=yes pkg install \
    nginx \
    >/dev/null 2>&1
echo "include /mnt/configs/web/nginx.conf;" > "${jail_root}/usr/local/etc/nginx/nginx.conf"
sysrc -R "${jail_root}" nginx_enable="YES"

umount -F "${jail_dir}/mount/web.fstab"
return 0
}

#torrent nzb sonarr etc
function jail_init_download {

local altroot=${ALTROOT:-${altroot:-""}}
local jail_dir=${JAIL_DIR:-${jail_dir:-"${altroot}/usr/local/jails"}}
jail_root="${jail_dir}/mount/download"
mount -F "${jail_dir}/mount/download.fstab"

chroot "${jail_root}" ASSUME_ALWAYS_YES=yes pkg install \
    nzbget \
    sonarr \
    python \
    py27-sqlite3 \
    fpc-libcurl \
    docbook-xml \
    >/dev/null 2>&1

chroot "${jail_root}" ln -s /usr/local/bin/python /usr/bin/python
chroot "${jail_root}" cd /usr/local && git clone https://github.com/CouchPotato/CouchPotatoServer.git
chroot "${jail_root}" cp /usr/local/CouchPotatoServer/init/freebsd /usr/local/etc/rc.d/couchpotato
chroot "${jail_root}" chmod 555 /usr/local/etc/rc.d/couchpotato
chroot "${JAIL_ROOT}" portmaster net-p2p/deluge


umount -F "${jail_dir}/mount/download.fstab"
return 0
}

#plex/emby etc
function jail_init_media {

return 0
}

#windows shares
function jail_init_share {

return 0
}

#tbd
function jail_init_dashboard {

return 0
}

