#!/bin/sh

set -o errexit
set -o nounset

fstab_init () {

    local altroot=${1:-${ALTROOT:-${altroot:-}}}
    local backup_nfs=${BACKUP_NFS:-${backup_nfs:-}}

    if [ -z "${backup_nfs}" ]
    then
        echo >&2 "****failed to create fstab. backup_nfs not set****"
        return 1
    fi

    echo "${backup_nfs} /mnt/backup nfs rw 0 0" > "${altroot}/etc/fstab"

    echo "    fstab updated"

    return 0
}
