#!/bin/bash

initialize_docker() {
    echo "deb [arch=amd64] https://download.docker.com/linux/$dist $release stable" \
        >  "$root/etc/apt/sources.list.d/docker.$release.list"
    eval "$chroot_eval curl -fsSL https://download.docker.com/linux/$dist/gpg | \
          $chroot_eval apt-key add -"
    eval "$chroot_eval apt-get update -qq"
    eval "$chroot_eval apt-get install -qq docker-ce"

    [ ! -d "$root/etc/docker/compose/$hostname" ] \
        && mkdir -p "$root/etc/docker/compose/$hostname"
    [ -f "$root/etc/docker/compose/$hostname/docker-compose.yml" ] && \
        rm "$root/etc/docker/compose/$hostname/docker-compose.yml"
    [ ! -L "$root/etc/docker/compose/$hostname/docker-compose.yml" ] && \
        ln -s "${SERVER_INSTALL:-~/server}/config/docker-compose.yml" \
            "$root/etc/docker/compose/$hostname/docker-compose.yml"

    # "update"

    eval "$chroot_eval systemctl enable docker-compose@$hostname"

    usermod -R "$root" -g docker $admin_username
}