#!/bin/bash

initialize_efi_grub() {
    echo "formating efi partition"
    mkfs.fat -n EFI -F32 ${boot_disk}1 >/dev/null
    sleep 1s
    echo "setting up system for efi"
    [ ! -d "$root/boot/efi" ] && mkdir -p "$root/boot/efi"
    echo "PARTUUID=$(trim_disk_link $(get_disk_link ${boot_disk}1 partuuid)) /boot/efi vfat defaults 0 1" >> "$root/etc/fstab"
    eval "$chroot_eval mount /boot/efi"
    echo "installing efi grub"
    eval "$chroot_eval apt-get install -qq grub-efi-amd64"
    echo "updating initramfs >/dev/null"
    echo "for x in \$(cat /proc/cmdline); do" > "$root/usr/share/initramfs-tools/conf.d/zfs"
    echo "    case \$x in" >> "$root/usr/share/initramfs-tools/conf.d/zfs"
    echo "        root=ZFS=*)" >> "$root/usr/share/initramfs-tools/conf.d/zfs"
    echo "            BOOT=zfs;;" >> "$root/usr/share/initramfs-tools/conf.d/zfs"
    echo "    esac" >> "$root/usr/share/initramfs-tools/conf.d/zfs"
    echo "done" >> "$root/usr/share/initramfs-tools/conf.d/zfs"

    eval "$chroot_eval update-initramfs -u -k all >/dev/null"
    echo "updating grub config"
    eval "$chroot_eval update-grub >/dev/null"
    echo "installing efi grub"
    eval "$chroot_eval grub-install \
        --target=x86_64-efi \
        --efi-directory=/boot/efi \
        --bootloader-id=debian \
        --recheck \
        --no-floppy >/dev/null"
    sleep 1s
    eval "$chroot_eval umount /boot/efi"
    echo "efi grub setup complete"
}