#!/usr/bin/env bash

set -o errexit
set -o nounset

export ASSUME_ALWAYS_YES=YES
export PAGER=cat

fast_drive_list="ada0"
root_drive_list="da0 da1"
backup_nfs="server-nas.flanneryonline.com:/volume1/backup"
software_list="ctags cscope curl expat libnghttp2 ca_root_nss pcre git-lite zsh zfsnap2"
delete_drive_list="${root_drive_list} ${fast_drive_list}"

release=${RELEASE:-"11.0-RELEASE"}
arch=${ARCH:-$(uname -m)}

altroot=${ALTROOT:-"/mnt"}
temp_dir=${TEMP_DIR:-"/var/tmp/install"}
zcache=${ZCACHE:-"${temp_dir}/zpool.cache"}

base_jail_dir=${BASE_JAIL_DIR:-"/usr/jails"}
jail_dir=${JAIL_DIR:-"${altroot}${base_jail_dir}"}
base_port_dir=${BASE_PORT_DIR:-"/usr/ports"}
port_dir=${PORT_DIR:-"${altroot}${base_port_dir}"}

root_pool=${ROOT_POOL:-"zroot"}
fast_pool=${FAST_POOL:-"zfast"}
storage_pool=${STORAGE_POOL:-"zstorage"}

media_zfs=${MEDIA_ZFS:-"${storage_pool}/media"}
media_dir=${MEDIA_DIR:-"/mnt/media"}
download_zfs=${DOWNLOAD_ZFS:-"${storage_pool}/download"}
download_dir=${DOWNLOAD_DIR:-"/mnt/download"}

config_zfs=${CONFIG_ZFS:-"${storage_pool}/config"}
config_dir=${CONFIG_DIR:-"/mnt/config"}
share_zfs=${SHARE_ZFS:-"${storage_pool}/share"}
share_dir=${SHARE_DIR:-"/mnt/share"}

port_zfs=${PORT_ZFS:-"${fast_pool}/ports"}
jail_zfs=${JAIL_ZFS:-"${fast_pool}/jails"}

gateway=${GATEWAY:-"10.0.0.1"}
subnet=${SUBNET:-"255.0.0.0"}
domain=${DOMAIN:-"flanneryonline.com"}
hostname=${SERVER_HOSTNAME:-"hostserver${t:-}"}
fqdn="${hostname}.${domain}"
host_ip=$(host "${fqdn}" | grep "has address" | awk '{print $4}')

if [[ "${TESTING:-"YES"}" = "NO" ]] ; then t=""; else t="test"; fi

if [[ -z ${host_ip// } ]]
then
    echo "Hostname ${fqdn} not found in DNS - setup DNS first."
    exit 1 
fi

#dialog box here?

if [[ -d "${temp_dir}" ]] ; then rm -R "${temp_dir}"; fi
mkdir -p "${temp_dir}"

source ~/server/scripts/zfs/init

source ~/server/scripts/system/install

source ~/server/scripts/etc/cron_init
source ~/server/scripts/etc/fstab_init
source ~/server/scripts/etc/jail_conf_init
source ~/server/scripts/etc/loader_conf_init
source ~/server/scripts/etc/make_conf_init
source ~/server/scripts/etc/periodic_conf_init
source ~/server/scripts/etc/rc_conf_init
source ~/server/scripts/etc/resolv_conf_init
source ~/server/scripts/etc/sshd_config_init
source ~/server/scripts/etc/ssmtp_conf_init
source ~/server/scripts/etc/user_init
source ~/server/scripts/etc/rc_conf_init

echo "Setting up ZFS."
zfs_init

echo "Installing system."
system_install "${altroot}" 1 1

echo "Configuring system."
cron_init
fstab_init
loader_conf_init
make_conf_init
periodic_conf_init
resolv_conf_init
sshd_config_init
ssmtp_conf_init
jail_conf_init
user_init
rc_conf_init

echo ""
zfs snapshot -r zroot@install
zfs snapshot -r zfast@install

echo "Cleaning up..."
cp "${zcache}" "${altroot}/boot/zfs/zpool.cache"
rm -R "${temp_dir}"

echo "Syncing."
sync

echo "Done!"
exit 0

