#!/bin/bash

zfs_create_new_root() {
    altroot=$(zpool get -H altroot $root_pool | cut -f 3)
    [ "$altroot" = "-" ] && altroot=""
    ! zfs list -H -o name | grep "$boot_pool/ROOT/$dist" >/dev/null && \
        zfs create -o canmount=off -o mountpoint=none $root_pool/ROOT/$dist
    if zfs list -H -o name | grep "$boot_pool/ROOT/$dist/$release" >/dev/null; then
        zfs snap $boot_pool/ROOT/$dist/$release@backup
        zfs clone $boot_pool/ROOT/$dist/$release@backup $boot_pool/ROOT/$dist/$release-$date
        zfs destroy $boot_pool/ROOT/$dist/$release@backup
        zfs destroy $boot_pool/ROOT/$dist/$release
    fi
    zfs create -o canmount=off -o mountpoint=none $root_pool/ROOT/$dist/$release

    #check if $dist/$release exists
    #   if so
    #       create snapshot
    #       delete everything
    #   if not
    #       create it
    zfs create -o canmount=noauto -o mountpoint="$root" $root_pool/ROOT/$dist/$release

    zfs mount $root_pool/ROOT/$dist/$release

}