#!/bin/bash

#requires variables:
#   docker_disk
#       must be set to list of dev disk ex: "/dev/sda"
#   docker_pool
#       zfs pool name for root ex: "zdocker"
zfs_docker_setup() {
    echo "clearing docker disk"
    clear_disk $docker_disk
    sleep 1s
    echo "creating docker pool"
    eval "zpool create -f -o ashift=13 \
        -O atime=off -O compression=lz4 \
        -O mountpoint=none -O canmount=off \
        -R "$root" \
        $docker_pool $(get_disk_link $docker_disk)"
    echo "docker disk setup complete"
    zfs create -o mountpoint=/var/lib/docker $docker_pool/main
}