#!/bin/bash

#requires variables:
#   storage_disks
#       must be set to list of dev disk ex: "/dev/sda /dev/sdb"
#   storage_pool
#       zfs pool name for root ex: "zstorage"
zfs_storage_setup() {
    storage_disk_list=
    space=
    echo "clearing all storage disks"
    for storage_disk in $storage_disks; do
        echo "clearing disk: $storage_disk"
        clear_disk $storage_disk
        sleep 1s
        storage_disk_list="${storage_disk_list:-}${space:-}$(get_disk_link $storage_disk)"
        space=" "
    done
    echo "creating storage pool"
    eval "zpool create -f -o ashift=12 \
        -O atime=off -O compression=lz4 \
        -O mountpoint=/storage \
        -R "$root" \
        $storage_pool raidz $storage_disk_list"
    zfs create $storage_pool/media
    zfs create $storage_pool/media/shows
    zfs create $storage_pool/media/shows/main
    zfs create $storage_pool/media/shows/other
    zfs create $storage_pool/media/shows/mandy
    zfs create $storage_pool/media/shows/pat
    zfs create $storage_pool/media/movies
    zfs create $storage_pool/media/movies/main
    zfs create $storage_pool/media/movies/standup
    zfs create $storage_pool/media/movies/documentary
    zfs create $storage_pool/media/movies/music
    zfs create $storage_pool/downloads
    zfs create $storage_pool/shares
    zfs create $storage_pool/configs
    zfs create $storage_pool/configs/nextcloud
    zfs create $storage_pool/configs/mariadb
    zfs create $storage_pool/configs/portainer
    zfs create $storage_pool/configs/plex
    zfs create $storage_pool/configs/plexpy
    zfs create $storage_pool/configs/ombi
    zfs create $storage_pool/configs/radarr
    zfs create $storage_pool/configs/sonarr
    zfs create $storage_pool/configs/nzbget
    zfs create $storage_pool/configs/nginx
    zfs create $storage_pool/configs/nginx-letsencrypt
    zfs create $storage_pool/configs/nginx-watcher
    echo "storage disk setup complete"
}