#!/bin/bash

#makes sure zfs is setup on host
initialize_zfs() {
    echo "deb [arch=amd64] $sec_url $release/updates $comp_spaces" \
        > "/etc/apt/sources.list.d/$dist.$release-updates.list"
    echo "deb [arch=amd64] $dist_url $release-updates $comp_spaces" \
        >> "/etc/apt/sources.list.d/$dist.$release-updates.list"
    echo "deb [arch=amd64] $dist_url $release-backports $comp_spaces" \
        > "/etc/apt/sources.list.d/$dist.$release-backports.list"
    echo "deb [arch=amd64] $dist_url $release $comp_spaces" \
        > "/etc/apt/sources.list.d/$dist.$release.list"
    apt-get update -qq
    apt-get install -qq gdisk linux-headers-amd64 zfs-dkms
    modprobe zfs
}