#!/bin/bash

#requires variables:
#   boot_disk
#       must be set to dev disk ex: "/dev/sda"
#   root_pool
#       zfs pool name for root ex: "zroot"
zfs_boot_setup() {
    echo "clearing boot disk"
    clear_disk $boot_disk
    echo "partitioning boot disk"
    sleep 1s
    parted -s $boot_disk "mktable gpt"
    parted -s $boot_disk "mkpart primary 1mb 513mb"
    parted -s $boot_disk "mkpart primary 513mb -1"
    parted -s $boot_disk "name 1 efi"
    parted -s $boot_disk "set 1 boot on"
    parted -s $boot_disk "name 2 system"
    parted -s $boot_disk "set 2 bios_grub on"
    echo "creating zfs boot pool"
    sleep 1s
    eval "zpool create -f \
        -o ashift=13 \
        -O atime=off \
        -O compression=lz4 \
        -O canmount=off
        -m none \
        -R "$root" \
        $root_pool $(get_disk_link ${boot_disk}2)"
    echo "setting up boot datasets"
    zfs create -o canmount=off -o mountpoint=none $root_pool/ROOT
    zfs create -o mountpoint=/home -o setuid=off $root_pool/home
    zfs create -o mountpoint=/root -o setuid=off $root_pool/home/root
    echo "boot disk setup complete"
}