version: '3.2'

volumes:
    nextcloud:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $STORAGE_CONFIG_DIR/nextcloud
    db:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $STORAGE_CONFIG_DIR/nextcloud/db

services:
    nextcloud_db:
        image: mariadb
        restart: always
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_password
            - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
        secrets:
            - mysql_password

    nextcloud:
        image: nextcloud
        restart: always
        ports:
            - 8077:80
        volumes:
            - nextcloud:/var/www/html
        depends_on:
            - nextcloud_db
        environment:
            - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            - MYSQL_HOST=nextcloud_db
            - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
            - NEXTCLOUD_ADMIN_USER=$ADMIN_USERNAME
        secrets:
            - nextcloud_admin_password
            - mysql_password

secrets:
    nextcloud_admin_password:
        file: $STORAGE_SETTINGS_DIR/nextcloud_admin_password
    mysql_password:
        file: $STORAGE_SETTINGS_DIR/mysql_password