version: '3'
services:
  pia:
    image: dperson/openvpn-client
    command: -r 10.0.0.0/8 -f "" -d
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 6789:6789       #nzbget
      - 8112:8112       #deluge
      - 58846:58846     #deluge
      - 58946:58946     #deluge
      - 58946:58946/udp #deluge
      - 5075:5075       #hydra
      - 9117:9117       #jackett
      - 8989:8989       #sonarr
      - 7878:7878       #radarr
    tmpfs:
      - /tmp
    security_opt:
      - label:disable
    domainname: ${SERVER_DOMAIN}
    volumes:
      - ${STORAGE_CONFIG_DIR}/pia:/vpn
    environment:
      - REGION=US Midwest
      - TZ=${SERVER_TIMEZONE}
  nzbget:
    image: linuxserver/nzbget
    depends_on:
      - pia
    network_mode: service:pia
    domainname: ${SERVER_DOMAIN}
    volumes:
      - ${STORAGE_CONFIG_DIR}/nzbget:/config
      - ${STORAGE_DOWNLOAD_DIR}:/downloads
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${SERVER_TIMEZONE}
  deluge:
    image: linuxserver/deluge
    depends_on:
      - pia
    network_mode: service:pia
    domainname: ${SERVER_DOMAIN}
    volumes:
      - ${STORAGE_CONFIG_DIR}/deluge:/config
      - ${STORAGE_DOWNLOAD_DIR}:/downloads
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${SERVER_TIMEZONE}
  hydra:
    image: linuxserver/hydra
    depends_on:
      - pia
    network_mode: service:pia
    domainname: ${SERVER_DOMAIN}
    volumes:
      - ${STORAGE_CONFIG_DIR}/hydra:/config
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${SERVER_TIMEZONE}
  jackett:
    image: linuxserver/jackett
    depends_on:
      - pia
    network_mode: service:pia
    domainname: ${SERVER_DOMAIN}
    volumes:
      - ${STORAGE_CONFIG_DIR}/jackett:/config
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${SERVER_TIMEZONE}
  sonarr:
    image: linuxserver/sonarr
    depends_on:
      - pia
    network_mode: service:pia
    domainname: ${SERVER_DOMAIN}
    volumes:
      - ${STORAGE_CONFIG_DIR}/sonarr:/config
      - ${STORAGE_MEDIA_DIR}/shows:/shows
      - ${STORAGE_DOWNLOAD_DIR}:/downloads
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${SERVER_TIMEZONE}
  radarr:
    image: linuxserver/radarr
    depends_on:
      - pia
    network_mode: service:pia
    domainname: ${SERVER_DOMAIN}
    volumes:
      - ${STORAGE_CONFIG_DIR}/radarr:/config
      - ${STORAGE_MEDIA_DIR}/movies:/movies
      - ${STORAGE_DOWNLOAD_DIR}:/downloads
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${SERVER_TIMEZONE}