#!/usr/bin/env bash

set -o errexit
set -o nounset

source ~/server/include/networking/etc/resolv_conf_init

function networking_init {

resolv_conf_init

sysrc -R "${altroot}" defaultrouter="${gateway}" >/dev/null 2>&1
sysrc -R "${altroot}" hostname="${fqdn}" >/dev/null 2>&1

return 0
}
