#!/bin/sh

set -o errexit
set -o nounset

lagg_init () {

    local altroot=${1:-${ALTROOT:-${altroot:-}}}

    for net in $(ifconfig | grep -v LOOPBACK | grep flags | cut -d: -f1)
    do
        sysrc -R "${altroot}" "ifconfig_${net}=\"up\""
        local lag_string="${lag_string:-"laggproto lacp"} laggport ${net}"
    done
    sysrc -R "${altroot}" ifconfig_lagg0="inet ${HOST_IP} netmask ${SUBNET} ${lag_string}"
}