#!/bin/sh

set -o errexit
set -o nounset

. ~/server/include/system/etc/cron_init
. ~/server/include/system/etc/fstab_init
. ~/server/include/system/etc/periodic_conf_init
. ~/server/include/system/etc/rc_conf_init

system_install () {

    cron_init
    fstab_init
    periodic_conf_init
    rc_conf_init

    return 0
}
