#!/usr/bin/env bash

set -o errexit
set -o nounset

source ~/server/include/system/etc/cron_init
source ~/server/include/system/etc/fstab_init
source ~/server/include/system/etc/periodic_conf_init
source ~/server/include/system/etc/rc_conf_init

function system_install {

    cron_init
    fstab_init
    periodic_conf_init
    rc_conf_init

    return 0
}
