#!/bin/sh

set -o errexit
set -o nounset

system_install () {

    local root=${1:-}
    local kernel=${2:-0}
    local ports=${3:-0}
    local ports_dir=${PORTS_DIR:-${ports_dir:-"/usr/ports"}}
    local temp_dir=${temp_dir:-"/var/tmp"}
    local valid_arch="amd64 arm i386"
    local valid_release_num="10.3 11.0"
    local arch_valid=0
    local release_valid=0

    if [ -z "${root}" ]
    then
        echo >&2 "****Failed to install system. No value passed for install location.****"
        return 1
    fi

    for arch_check in ${valid_arch}
    do
        if [[ ${arch} = ${arch_check} ]]
        then
            local arch_valid=1
        fi
    done
    for release_check_num in ${valid_release_num}
    do
        if [ ${release} = ${release_check_num}-RELEASE ]
        then
            local release_valid=1
        fi
    done
    if [ $release_valid -ne 1 -o $arch_valid -ne 1 -o ! -d "${root}" ]
    then
        echo >&2 "****Failed to install system. Release, architecture, or root location invalid.****"
        return 1
    fi

    echo "  --Installing FreeBSD version ${release} for ${arch} to ${root}."
    if [ ${kernel} -eq 1 ] ; then echo "     -with kernel"; fi
    if [ ${ports} -eq 1 ] ; then echo "     -with ports"; fi

    if [ ! -f "${temp_dir}/base-${release}.txz" ]
    then
        curl -fLo "${temp_dir}/base-${release}.txz" "ftp://ftp.freebsd.org/pub/FreeBSD/releases/${arch}/${release}/base.txz"
    fi

    if [ ${kernel} -eq 1 ]
    then
        if [[ ! -f "${temp_dir}/kernel-${release}.txz" ]]
        then
            curl -fLo "${temp_dir}/kernel-${release}.txz" "ftp://ftp.freebsd.org/pub/FreeBSD/releases/${arch}/${release}/kernel.txz"
        fi
    fi
    if [ ${ports} -eq 1 ]
    then
        if [[ ! -f "${temp_dir}/ports-${release}.txz" ]]
        then
            curl -fLo "${temp_dir}/ports-${release}.txz" "ftp://ftp.freebsd.org/pub/FreeBSD/releases/${arch}/${release}/ports.txz"
        fi
    fi

    echo "    Installing base. Please wait..."
    pv "${temp_dir}/base-${release}.txz" | tar -xf - -C "${root}"
    if [ ${kernel} -eq 1 ]
    then
        echo "    Installing kernel. Please wait..."
        pv "${temp_dir}/kernel-${release}.txz" | tar -xf - -C "${root}"
    fi
    if [ ${ports} -eq 1 ]
    then
        echo "    Installing ports. Please wait..."
        pv "${temp_dir}/ports-${release}.txz" | tar -xf - -C "${root}"
    fi

    if [ ${REMOVE_INSTALL_FILES:-1} -eq 1 ]
    then
        echo "    Removing temp files."
        rm "${temp_dir}/base-${release}.txz"
        if [ ${kernel} -eq 1 ]
        then
            rm "${temp_dir}/kernel-${release}.txz"
        fi
        if [ ${ports} -eq 1 ]
        then
            rm "${temp_dir}/ports-${release}.txz"
        fi
    fi

    echo "    Updating system to latest."
    freebsd-update -b "${root}" fetch install >/dev/null 2>&1

    echo "    Install successful!"
    return 0
}
