#!/usr/bin/env bash

set -o errexit
set -o nounset

function clean_disk {

    # No args? More than 1 arg?
    if [[ $# -ne 1 ]]
    then
        echo "****Failed to clean disk. invalid number of arquments.****"
        return 1
    fi

    local drive=$1

    # Check if arg is a drive
    if [[ ! -e /dev/${drive} ]]
    then 
        echo "****Failed to delete $drive - not a drive****"
        return 1
    fi

    if ! gpart show ${drive} >/dev/null 2>&1
    then
        echo "    $drive seems to already be clean."
        return 0
    fi

    echo "    destroying drive $drive"
    gpart destroy -F ${drive} >/dev/null 2>&1

    return 0
}
