#!/usr/bin/env bash

set -o errexit
set -o nounset

source ~/server/include/zfs/clean_disk
source ~/server/include/zfs/create_pool

source ~/server/include/zfs/etc/loader_conf_init

source ~/server/include/zfs/datasets/zroot
source ~/server/include/zfs/datasets/zfast
source ~/server/include/zfs/datasets/zstorage
source ~/server/include/zfs/datasets/extra


function zfs_init {

    local root_drive_list=${ROOT_DRIVE_LIST:-${root_drive_list}}
    local fast_drive_list=${FAST_DRIVE_LIST:-${fast_drive_list}}
    local rool_pool=${ROOT_POOL:-${root_pool:-"zroot"}}
    local fast_pool=${FAST_POOL:-${fast_pool:-"zfast"}}
    local storage_pool=${storage_POOL:-${storage_pool:-"zstorage"}}

    if zpool list "${fast_pool}" >/dev/null 2>&1
    then
        echo "    ${fast_pool} pool already exists - destroying!"
        zpool destroy -f "${fast_pool}" >/dev/null 2>&1
    fi
    if zpool list "${rool_pool}" >/dev/null 2>&1
    then
        echo "    ${rool_pool} pool already exists - destroying!"
        zpool destroy -f "${rool_pool}" >/dev/null 2>&1
    fi

    for disk in ${root_drive_list} ${fast_drive_list}
    do
        echo "    Cleaning ${disk}..."
        clean_disk $disk
    done

    echo "    Starting ZFS setup."

    create_pool "$rool_pool" "mirror" "${root_drive_list}" 1
    create_pool "$fast_pool" "" "${fast_drive_list}" 0

    #storage pool stuff?

    zroot_datasets
    zfast_datasets
    zstorage_datasets
    extra_datasets

    loader_conf_init

    echo "    ZFS setup complete."

    return 0

}
