#!/usr/bin/env bash

set -o errexit
set -o nounset

function zroot_reset {

zpool export zroot
for gpt_nop in /dev/gpt/boot*.nop
do
    gnop destroy "${gpt_nop}"
done

zpool import -m none -o altroot="${altroot}" -c "${zcache}" zroot

zpool set bootfs=zroot/root/current zroot

return 0
}
